// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module bnn_top_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        WF1_address0,
        WF1_ce0,
        WF1_q0,
        TAUF1_address0,
        TAUF1_ce0,
        TAUF1_q0,
        f1_address0,
        f1_ce0,
        f1_we0,
        f1_d0,
        l3_address0,
        l3_ce0,
        l3_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] WF1_address0;
output   WF1_ce0;
input  [31:0] WF1_q0;
output  [6:0] TAUF1_address0;
output   TAUF1_ce0;
input  [31:0] TAUF1_q0;
output  [6:0] f1_address0;
output   f1_ce0;
output   f1_we0;
output  [0:0] f1_d0;
output  [9:0] l3_address0;
output   l3_ce0;
input  [0:0] l3_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln140_fu_154_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln142_fu_172_p2;
reg   [0:0] icmp_ln142_reg_367;
wire   [4:0] trunc_ln145_1_fu_215_p1;
reg   [4:0] trunc_ln145_1_reg_377;
wire   [0:0] icmp_ln142_1_fu_248_p2;
reg   [0:0] icmp_ln142_1_reg_387;
reg   [6:0] f1_addr_reg_396;
wire   [63:0] zext_ln142_fu_210_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln145_fu_237_p1;
wire   [63:0] zext_ln140_fu_200_p1;
reg   [11:0] acc_11_fu_64;
wire   [11:0] acc_fu_306_p2;
wire    ap_loop_init;
reg   [10:0] k_1_fu_68;
wire   [10:0] add_ln142_fu_242_p2;
reg   [7:0] n_fu_72;
wire   [7:0] select_ln140_2_fu_192_p3;
reg   [17:0] indvar_flatten73_fu_76;
wire   [17:0] add_ln140_fu_160_p2;
reg    l3_ce0_local;
reg    WF1_ce0_local;
reg    TAUF1_ce0_local;
reg    f1_we0_local;
wire   [0:0] icmp_ln148_fu_324_p2;
reg    f1_ce0_local;
wire   [7:0] add_ln140_1_fu_186_p2;
wire   [10:0] select_ln140_fu_178_p3;
wire   [6:0] trunc_ln145_fu_206_p1;
wire   [4:0] tmp_s_fu_219_p4;
wire   [11:0] lshr_ln4_fu_229_p3;
wire   [31:0] zext_ln145_1_fu_279_p1;
wire   [31:0] lshr_ln145_fu_282_p2;
wire   [0:0] w_fu_288_p1;
wire   [0:0] xor_ln146_fu_292_p2;
wire   [11:0] select_ln146_fu_298_p3;
wire   [11:0] select_ln140_1_fu_272_p3;
wire   [19:0] shl_ln6_fu_312_p3;
wire  signed [31:0] sext_ln148_fu_320_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 acc_11_fu_64 = 12'd0;
#0 k_1_fu_68 = 11'd0;
#0 n_fu_72 = 8'd0;
#0 indvar_flatten73_fu_76 = 18'd0;
#0 ap_done_reg = 1'b0;
end

bnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_11_fu_64 <= 12'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            acc_11_fu_64 <= acc_fu_306_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten73_fu_76 <= 18'd0;
        end else if (((icmp_ln140_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten73_fu_76 <= add_ln140_fu_160_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_1_fu_68 <= 11'd0;
        end else if (((icmp_ln140_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_1_fu_68 <= add_ln142_fu_242_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            n_fu_72 <= 8'd0;
        end else if (((icmp_ln140_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            n_fu_72 <= select_ln140_2_fu_192_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        f1_addr_reg_396 <= zext_ln140_fu_200_p1;
        icmp_ln142_1_reg_387 <= icmp_ln142_1_fu_248_p2;
        icmp_ln142_reg_367 <= icmp_ln142_fu_172_p2;
        trunc_ln145_1_reg_377 <= trunc_ln145_1_fu_215_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TAUF1_ce0_local = 1'b1;
    end else begin
        TAUF1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        WF1_ce0_local = 1'b1;
    end else begin
        WF1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln140_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        f1_ce0_local = 1'b1;
    end else begin
        f1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_1_reg_387 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        f1_we0_local = 1'b1;
    end else begin
        f1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        l3_ce0_local = 1'b1;
    end else begin
        l3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TAUF1_address0 = zext_ln140_fu_200_p1;

assign TAUF1_ce0 = TAUF1_ce0_local;

assign WF1_address0 = zext_ln145_fu_237_p1;

assign WF1_ce0 = WF1_ce0_local;

assign acc_fu_306_p2 = (select_ln146_fu_298_p3 + select_ln140_1_fu_272_p3);

assign add_ln140_1_fu_186_p2 = (n_fu_72 + 8'd1);

assign add_ln140_fu_160_p2 = (indvar_flatten73_fu_76 + 18'd1);

assign add_ln142_fu_242_p2 = (select_ln140_fu_178_p3 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign f1_address0 = f1_addr_reg_396;

assign f1_ce0 = f1_ce0_local;

assign f1_d0 = icmp_ln148_fu_324_p2;

assign f1_we0 = f1_we0_local;

assign icmp_ln140_fu_154_p2 = ((indvar_flatten73_fu_76 == 18'd131072) ? 1'b1 : 1'b0);

assign icmp_ln142_1_fu_248_p2 = ((add_ln142_fu_242_p2 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln142_fu_172_p2 = ((k_1_fu_68 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_324_p2 = (($signed(sext_ln148_fu_320_p1) > $signed(TAUF1_q0)) ? 1'b1 : 1'b0);

assign l3_address0 = zext_ln142_fu_210_p1;

assign l3_ce0 = l3_ce0_local;

assign lshr_ln145_fu_282_p2 = WF1_q0 >> zext_ln145_1_fu_279_p1;

assign lshr_ln4_fu_229_p3 = {{trunc_ln145_fu_206_p1}, {tmp_s_fu_219_p4}};

assign select_ln140_1_fu_272_p3 = ((icmp_ln142_reg_367[0:0] == 1'b1) ? 12'd0 : acc_11_fu_64);

assign select_ln140_2_fu_192_p3 = ((icmp_ln142_fu_172_p2[0:0] == 1'b1) ? add_ln140_1_fu_186_p2 : n_fu_72);

assign select_ln140_fu_178_p3 = ((icmp_ln142_fu_172_p2[0:0] == 1'b1) ? 11'd0 : k_1_fu_68);

assign select_ln146_fu_298_p3 = ((xor_ln146_fu_292_p2[0:0] == 1'b1) ? 12'd4095 : 12'd1);

assign sext_ln148_fu_320_p1 = $signed(shl_ln6_fu_312_p3);

assign shl_ln6_fu_312_p3 = {{acc_fu_306_p2}, {8'd0}};

assign tmp_s_fu_219_p4 = {{select_ln140_fu_178_p3[9:5]}};

assign trunc_ln145_1_fu_215_p1 = select_ln140_fu_178_p3[4:0];

assign trunc_ln145_fu_206_p1 = select_ln140_2_fu_192_p3[6:0];

assign w_fu_288_p1 = lshr_ln145_fu_282_p2[0:0];

assign xor_ln146_fu_292_p2 = (w_fu_288_p1 ^ l3_q0);

assign zext_ln140_fu_200_p1 = select_ln140_2_fu_192_p3;

assign zext_ln142_fu_210_p1 = select_ln140_fu_178_p3;

assign zext_ln145_1_fu_279_p1 = trunc_ln145_1_reg_377;

assign zext_ln145_fu_237_p1 = lshr_ln4_fu_229_p3;

endmodule //bnn_top_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25
