// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module bnn_top_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln135,
        oc_2,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1,
        l3_address0,
        l3_ce0,
        l3_we0,
        l3_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sext_ln135;
input  [5:0] oc_2;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1;
output  [9:0] l3_address0;
output   l3_ce0;
output   l3_we0;
output  [0:0] l3_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln127_fu_354_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [39:0] sext_ln135_cast_fu_332_p1;
reg  signed [39:0] sext_ln135_cast_reg_856;
wire   [2:0] select_ln127_fu_378_p3;
reg   [2:0] select_ln127_reg_865;
reg   [2:0] select_ln127_reg_865_pp0_iter1_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter2_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter3_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter4_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter5_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter6_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter7_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter8_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter9_reg;
reg   [2:0] select_ln127_reg_865_pp0_iter10_reg;
wire   [1:0] trunc_ln130_fu_400_p1;
reg   [1:0] trunc_ln130_reg_870;
reg   [1:0] trunc_ln130_reg_870_pp0_iter1_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter2_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter3_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter4_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter5_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter6_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter7_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter8_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter9_reg;
reg   [1:0] trunc_ln130_reg_870_pp0_iter10_reg;
wire   [1:0] trunc_ln130_1_fu_430_p1;
reg   [1:0] trunc_ln130_1_reg_878;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter1_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter2_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter3_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter4_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter5_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter6_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter7_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter8_reg;
reg   [1:0] trunc_ln130_1_reg_878_pp0_iter9_reg;
wire   [4:0] add_ln130_fu_444_p2;
reg   [3:0] tmp_51_reg_890;
reg   [3:0] tmp_51_reg_890_pp0_iter4_reg;
reg   [3:0] tmp_51_reg_890_pp0_iter5_reg;
reg   [3:0] tmp_51_reg_890_pp0_iter6_reg;
reg   [3:0] tmp_51_reg_890_pp0_iter7_reg;
reg   [3:0] tmp_51_reg_890_pp0_iter8_reg;
wire   [2:0] trunc_ln130_2_fu_500_p1;
reg   [2:0] trunc_ln130_2_reg_895;
reg   [2:0] trunc_ln130_2_reg_895_pp0_iter9_reg;
reg   [2:0] trunc_ln130_2_reg_895_pp0_iter10_reg;
wire   [31:0] m_9_fu_689_p3;
reg   [31:0] m_9_reg_1003;
wire   [63:0] zext_ln130_5_fu_504_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln131_fu_542_p1;
wire   [63:0] zext_ln132_fu_635_p1;
wire   [63:0] zext_ln133_fu_674_p1;
wire   [63:0] zext_ln135_fu_816_p1;
reg   [2:0] pw_fu_90;
wire   [2:0] add_ln128_fu_470_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_pw_load;
reg   [2:0] ph_fu_94;
wire   [2:0] select_ln127_1_fu_392_p3;
reg   [2:0] ap_sig_allocacmp_ph_load;
reg   [4:0] indvar_flatten66_fu_98;
wire   [4:0] add_ln127_fu_360_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten66_load;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local;
reg    l3_we0_local;
wire   [0:0] icmp_ln135_fu_796_p2;
reg    l3_ce0_local;
wire   [0:0] icmp_ln128_fu_372_p2;
wire   [2:0] add_ln127_1_fu_386_p2;
wire   [3:0] tmp_fu_412_p3;
wire   [4:0] p_shl_fu_404_p3;
wire   [4:0] zext_ln130_fu_420_p1;
wire   [2:0] shl_ln130_fu_434_p2;
wire   [4:0] zext_ln130_1_fu_440_p1;
wire   [4:0] sub_ln130_fu_424_p2;
wire   [4:0] add_ln130_2_fu_454_p2;
wire   [3:0] grp_fu_464_p1;
wire   [12:0] tmp_51_fu_491_p1;
wire  signed [12:0] grp_fu_821_p3;
wire   [2:0] grp_fu_464_p2;
wire   [5:0] add_ln7_fu_512_p5;
wire   [5:0] mul_ln131_fu_526_p0;
wire   [7:0] mul_ln131_fu_526_p1;
wire   [12:0] mul_ln131_fu_526_p2;
wire   [3:0] tmp_52_fu_532_p4;
wire   [31:0] s0_fu_551_p11;
wire   [31:0] s1_fu_578_p11;
wire   [5:0] add_ln8_fu_605_p5;
wire   [5:0] mul_ln132_fu_619_p0;
wire   [7:0] mul_ln132_fu_619_p1;
wire   [12:0] mul_ln132_fu_619_p2;
wire   [3:0] tmp_53_fu_625_p4;
wire   [5:0] add_ln9_fu_644_p5;
wire   [5:0] mul_ln133_fu_658_p0;
wire   [7:0] mul_ln133_fu_658_p1;
wire   [12:0] mul_ln133_fu_658_p2;
wire   [3:0] tmp_54_fu_664_p4;
wire   [31:0] s1_fu_578_p13;
wire   [31:0] s0_fu_551_p13;
wire   [0:0] icmp_ln134_fu_683_p2;
wire   [3:0] shl_ln135_1_fu_697_p3;
wire   [31:0] s2_fu_708_p11;
wire   [31:0] s3_fu_735_p11;
wire   [31:0] s2_fu_708_p13;
wire   [0:0] icmp_ln134_1_fu_762_p2;
wire   [31:0] s3_fu_735_p13;
wire   [31:0] m_11_fu_767_p3;
wire   [0:0] icmp_ln134_2_fu_774_p2;
wire   [31:0] select_ln134_fu_780_p3;
wire   [39:0] shl_ln_fu_788_p3;
wire   [9:0] tmp12_fu_802_p4;
wire   [9:0] zext_ln128_fu_704_p1;
wire   [9:0] add_ln135_fu_810_p2;
wire   [4:0] grp_fu_821_p0;
wire   [4:0] grp_fu_821_p1;
wire   [6:0] grp_fu_821_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] grp_fu_821_p00;
wire   [5:0] grp_fu_821_p10;
wire   [12:0] mul_ln131_fu_526_p00;
wire   [12:0] mul_ln132_fu_619_p00;
wire   [12:0] mul_ln133_fu_658_p00;
wire   [2:0] s0_fu_551_p1;
wire   [2:0] s0_fu_551_p3;
wire   [2:0] s0_fu_551_p5;
wire   [2:0] s0_fu_551_p7;
wire  signed [2:0] s0_fu_551_p9;
wire  signed [2:0] s1_fu_578_p1;
wire   [2:0] s1_fu_578_p3;
wire   [2:0] s1_fu_578_p5;
wire   [2:0] s1_fu_578_p7;
wire   [2:0] s1_fu_578_p9;
wire   [2:0] s2_fu_708_p1;
wire   [2:0] s2_fu_708_p3;
wire  signed [2:0] s2_fu_708_p5;
wire   [2:0] s2_fu_708_p7;
wire   [2:0] s2_fu_708_p9;
wire   [2:0] s3_fu_735_p1;
wire   [2:0] s3_fu_735_p3;
wire   [2:0] s3_fu_735_p5;
wire  signed [2:0] s3_fu_735_p7;
wire   [2:0] s3_fu_735_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 pw_fu_90 = 3'd0;
#0 ph_fu_94 = 3'd0;
#0 indvar_flatten66_fu_98 = 5'd0;
#0 ap_done_reg = 1'b0;
end

bnn_top_urem_5ns_4ns_3_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_5ns_4ns_3_9_1_U153(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln130_fu_444_p2),
    .din1(grp_fu_464_p1),
    .ce(1'b1),
    .dout(grp_fu_464_p2)
);

bnn_top_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U154(
    .din0(mul_ln131_fu_526_p0),
    .din1(mul_ln131_fu_526_p1),
    .dout(mul_ln131_fu_526_p2)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U155(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1),
    .def(s0_fu_551_p11),
    .sel(trunc_ln130_2_reg_895_pp0_iter9_reg),
    .dout(s0_fu_551_p13)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h0 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h2 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h3 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U156(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1),
    .def(s1_fu_578_p11),
    .sel(trunc_ln130_2_reg_895_pp0_iter9_reg),
    .dout(s1_fu_578_p13)
);

bnn_top_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U157(
    .din0(mul_ln132_fu_619_p0),
    .din1(mul_ln132_fu_619_p1),
    .dout(mul_ln132_fu_619_p2)
);

bnn_top_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U158(
    .din0(mul_ln133_fu_658_p0),
    .din1(mul_ln133_fu_658_p1),
    .dout(mul_ln133_fu_658_p2)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h3 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h4 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h1 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U159(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0),
    .def(s2_fu_708_p11),
    .sel(trunc_ln130_2_reg_895_pp0_iter10_reg),
    .dout(s2_fu_708_p13)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h0 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_x_U160(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0),
    .def(s3_fu_735_p11),
    .sel(trunc_ln130_2_reg_895_pp0_iter10_reg),
    .dout(s3_fu_735_p13)
);

bnn_top_am_addmul_5ns_5ns_7ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 13 ))
am_addmul_5ns_5ns_7ns_13_4_1_U161(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_821_p0),
    .din1(grp_fu_821_p1),
    .din2(grp_fu_821_p2),
    .ce(1'b1),
    .dout(grp_fu_821_p3)
);

bnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln127_fu_354_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten66_fu_98 <= add_ln127_fu_360_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten66_fu_98 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln127_fu_354_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ph_fu_94 <= select_ln127_1_fu_392_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ph_fu_94 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln127_fu_354_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            pw_fu_90 <= add_ln128_fu_470_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            pw_fu_90 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        m_9_reg_1003 <= m_9_fu_689_p3;
        select_ln127_reg_865_pp0_iter10_reg <= select_ln127_reg_865_pp0_iter9_reg;
        select_ln127_reg_865_pp0_iter2_reg <= select_ln127_reg_865_pp0_iter1_reg;
        select_ln127_reg_865_pp0_iter3_reg <= select_ln127_reg_865_pp0_iter2_reg;
        select_ln127_reg_865_pp0_iter4_reg <= select_ln127_reg_865_pp0_iter3_reg;
        select_ln127_reg_865_pp0_iter5_reg <= select_ln127_reg_865_pp0_iter4_reg;
        select_ln127_reg_865_pp0_iter6_reg <= select_ln127_reg_865_pp0_iter5_reg;
        select_ln127_reg_865_pp0_iter7_reg <= select_ln127_reg_865_pp0_iter6_reg;
        select_ln127_reg_865_pp0_iter8_reg <= select_ln127_reg_865_pp0_iter7_reg;
        select_ln127_reg_865_pp0_iter9_reg <= select_ln127_reg_865_pp0_iter8_reg;
        tmp_51_reg_890 <= {{tmp_51_fu_491_p1[12:9]}};
        tmp_51_reg_890_pp0_iter4_reg <= tmp_51_reg_890;
        tmp_51_reg_890_pp0_iter5_reg <= tmp_51_reg_890_pp0_iter4_reg;
        tmp_51_reg_890_pp0_iter6_reg <= tmp_51_reg_890_pp0_iter5_reg;
        tmp_51_reg_890_pp0_iter7_reg <= tmp_51_reg_890_pp0_iter6_reg;
        tmp_51_reg_890_pp0_iter8_reg <= tmp_51_reg_890_pp0_iter7_reg;
        trunc_ln130_1_reg_878_pp0_iter2_reg <= trunc_ln130_1_reg_878_pp0_iter1_reg;
        trunc_ln130_1_reg_878_pp0_iter3_reg <= trunc_ln130_1_reg_878_pp0_iter2_reg;
        trunc_ln130_1_reg_878_pp0_iter4_reg <= trunc_ln130_1_reg_878_pp0_iter3_reg;
        trunc_ln130_1_reg_878_pp0_iter5_reg <= trunc_ln130_1_reg_878_pp0_iter4_reg;
        trunc_ln130_1_reg_878_pp0_iter6_reg <= trunc_ln130_1_reg_878_pp0_iter5_reg;
        trunc_ln130_1_reg_878_pp0_iter7_reg <= trunc_ln130_1_reg_878_pp0_iter6_reg;
        trunc_ln130_1_reg_878_pp0_iter8_reg <= trunc_ln130_1_reg_878_pp0_iter7_reg;
        trunc_ln130_1_reg_878_pp0_iter9_reg <= trunc_ln130_1_reg_878_pp0_iter8_reg;
        trunc_ln130_2_reg_895 <= trunc_ln130_2_fu_500_p1;
        trunc_ln130_2_reg_895_pp0_iter10_reg <= trunc_ln130_2_reg_895_pp0_iter9_reg;
        trunc_ln130_2_reg_895_pp0_iter9_reg <= trunc_ln130_2_reg_895;
        trunc_ln130_reg_870_pp0_iter10_reg <= trunc_ln130_reg_870_pp0_iter9_reg;
        trunc_ln130_reg_870_pp0_iter2_reg <= trunc_ln130_reg_870_pp0_iter1_reg;
        trunc_ln130_reg_870_pp0_iter3_reg <= trunc_ln130_reg_870_pp0_iter2_reg;
        trunc_ln130_reg_870_pp0_iter4_reg <= trunc_ln130_reg_870_pp0_iter3_reg;
        trunc_ln130_reg_870_pp0_iter5_reg <= trunc_ln130_reg_870_pp0_iter4_reg;
        trunc_ln130_reg_870_pp0_iter6_reg <= trunc_ln130_reg_870_pp0_iter5_reg;
        trunc_ln130_reg_870_pp0_iter7_reg <= trunc_ln130_reg_870_pp0_iter6_reg;
        trunc_ln130_reg_870_pp0_iter8_reg <= trunc_ln130_reg_870_pp0_iter7_reg;
        trunc_ln130_reg_870_pp0_iter9_reg <= trunc_ln130_reg_870_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln127_reg_865 <= select_ln127_fu_378_p3;
        select_ln127_reg_865_pp0_iter1_reg <= select_ln127_reg_865;
        sext_ln135_cast_reg_856 <= sext_ln135_cast_fu_332_p1;
        trunc_ln130_1_reg_878 <= trunc_ln130_1_fu_430_p1;
        trunc_ln130_1_reg_878_pp0_iter1_reg <= trunc_ln130_1_reg_878;
        trunc_ln130_reg_870 <= trunc_ln130_fu_400_p1;
        trunc_ln130_reg_870_pp0_iter1_reg <= trunc_ln130_reg_870;
    end
end

always @ (*) begin
    if (((icmp_ln127_fu_354_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten66_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten66_load = indvar_flatten66_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ph_load = 3'd0;
    end else begin
        ap_sig_allocacmp_ph_load = ph_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_pw_load = 3'd0;
    end else begin
        ap_sig_allocacmp_pw_load = pw_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = zext_ln133_fu_674_p1;
        end else if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = zext_ln132_fu_635_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895 == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = zext_ln131_fu_542_p1;
        end else if ((trunc_ln130_2_reg_895 == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = zext_ln130_5_fu_504_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd4)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd2)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = zext_ln133_fu_674_p1;
        end else if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = zext_ln132_fu_635_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895 == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = zext_ln131_fu_542_p1;
        end else if ((trunc_ln130_2_reg_895 == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = zext_ln130_5_fu_504_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd3)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd1)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = zext_ln133_fu_674_p1;
        end else if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = zext_ln132_fu_635_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895 == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = zext_ln131_fu_542_p1;
        end else if ((trunc_ln130_2_reg_895 == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = zext_ln130_5_fu_504_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd2)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd0)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = zext_ln133_fu_674_p1;
        end else if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = zext_ln132_fu_635_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895 == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = zext_ln131_fu_542_p1;
        end else if ((trunc_ln130_2_reg_895 == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = zext_ln130_5_fu_504_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd2)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd0)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = zext_ln133_fu_674_p1;
        end else if ((trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = zext_ln132_fu_635_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln130_2_reg_895 == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = zext_ln131_fu_542_p1;
        end else if ((trunc_ln130_2_reg_895 == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = zext_ln130_5_fu_504_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln130_2_reg_895_pp0_iter9_reg == 3'd0)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln130_2_reg_895 == 3'd3)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        l3_ce0_local = 1'b1;
    end else begin
        l3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        l3_we0_local = 1'b1;
    end else begin
        l3_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln127_1_fu_386_p2 = (ap_sig_allocacmp_ph_load + 3'd1);

assign add_ln127_fu_360_p2 = (ap_sig_allocacmp_indvar_flatten66_load + 5'd1);

assign add_ln128_fu_470_p2 = (select_ln127_fu_378_p3 + 3'd1);

assign add_ln130_2_fu_454_p2 = (p_shl_fu_404_p3 + zext_ln130_fu_420_p1);

assign add_ln130_fu_444_p2 = (zext_ln130_1_fu_440_p1 + sub_ln130_fu_424_p2);

assign add_ln135_fu_810_p2 = (tmp12_fu_802_p4 + zext_ln128_fu_704_p1);

assign add_ln7_fu_512_p5 = {{{{trunc_ln130_reg_870_pp0_iter8_reg}, {1'd0}}, {trunc_ln130_1_reg_878_pp0_iter8_reg}}, {1'd1}};

assign add_ln8_fu_605_p5 = {{{{trunc_ln130_reg_870_pp0_iter9_reg}, {1'd1}}, {trunc_ln130_1_reg_878_pp0_iter9_reg}}, {1'd0}};

assign add_ln9_fu_644_p5 = {{{{trunc_ln130_reg_870_pp0_iter9_reg}, {1'd1}}, {trunc_ln130_1_reg_878_pp0_iter9_reg}}, {1'd1}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local;

assign grp_fu_464_p1 = 5'd5;

assign grp_fu_821_p0 = grp_fu_821_p00;

assign grp_fu_821_p00 = add_ln130_fu_444_p2;

assign grp_fu_821_p1 = grp_fu_821_p10;

assign grp_fu_821_p10 = add_ln130_2_fu_454_p2;

assign grp_fu_821_p2 = 13'd103;

assign icmp_ln127_fu_354_p2 = ((ap_sig_allocacmp_indvar_flatten66_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln128_fu_372_p2 = ((ap_sig_allocacmp_pw_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln134_1_fu_762_p2 = (($signed(s2_fu_708_p13) > $signed(m_9_reg_1003)) ? 1'b1 : 1'b0);

assign icmp_ln134_2_fu_774_p2 = (($signed(s3_fu_735_p13) > $signed(m_11_fu_767_p3)) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_683_p2 = (($signed(s1_fu_578_p13) > $signed(s0_fu_551_p13)) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_796_p2 = (($signed(shl_ln_fu_788_p3) > $signed(sext_ln135_cast_reg_856)) ? 1'b1 : 1'b0);

assign l3_address0 = zext_ln135_fu_816_p1;

assign l3_ce0 = l3_ce0_local;

assign l3_d0 = icmp_ln135_fu_796_p2;

assign l3_we0 = l3_we0_local;

assign m_11_fu_767_p3 = ((icmp_ln134_1_fu_762_p2[0:0] == 1'b1) ? s2_fu_708_p13 : m_9_reg_1003);

assign m_9_fu_689_p3 = ((icmp_ln134_fu_683_p2[0:0] == 1'b1) ? s1_fu_578_p13 : s0_fu_551_p13);

assign mul_ln131_fu_526_p0 = mul_ln131_fu_526_p00;

assign mul_ln131_fu_526_p00 = add_ln7_fu_512_p5;

assign mul_ln131_fu_526_p1 = 13'd103;

assign mul_ln132_fu_619_p0 = mul_ln132_fu_619_p00;

assign mul_ln132_fu_619_p00 = add_ln8_fu_605_p5;

assign mul_ln132_fu_619_p1 = 13'd103;

assign mul_ln133_fu_658_p0 = mul_ln133_fu_658_p00;

assign mul_ln133_fu_658_p00 = add_ln9_fu_644_p5;

assign mul_ln133_fu_658_p1 = 13'd103;

assign p_shl_fu_404_p3 = {{trunc_ln130_fu_400_p1}, {3'd0}};

assign s0_fu_551_p11 = 'bx;

assign s1_fu_578_p11 = 'bx;

assign s2_fu_708_p11 = 'bx;

assign s3_fu_735_p11 = 'bx;

assign select_ln127_1_fu_392_p3 = ((icmp_ln128_fu_372_p2[0:0] == 1'b1) ? add_ln127_1_fu_386_p2 : ap_sig_allocacmp_ph_load);

assign select_ln127_fu_378_p3 = ((icmp_ln128_fu_372_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_pw_load);

assign select_ln134_fu_780_p3 = ((icmp_ln134_2_fu_774_p2[0:0] == 1'b1) ? s3_fu_735_p13 : m_11_fu_767_p3);

assign sext_ln135_cast_fu_332_p1 = $signed(sext_ln135);

assign shl_ln130_fu_434_p2 = select_ln127_fu_378_p3 << 3'd1;

assign shl_ln135_1_fu_697_p3 = {{trunc_ln130_reg_870_pp0_iter10_reg}, {2'd0}};

assign shl_ln_fu_788_p3 = {{select_ln134_fu_780_p3}, {8'd0}};

assign sub_ln130_fu_424_p2 = (p_shl_fu_404_p3 - zext_ln130_fu_420_p1);

assign tmp12_fu_802_p4 = {{{oc_2}, {1'd0}}, {select_ln127_reg_865_pp0_iter10_reg}};

assign tmp_51_fu_491_p1 = grp_fu_821_p3;

assign tmp_52_fu_532_p4 = {{mul_ln131_fu_526_p2[12:9]}};

assign tmp_53_fu_625_p4 = {{mul_ln132_fu_619_p2[12:9]}};

assign tmp_54_fu_664_p4 = {{mul_ln133_fu_658_p2[12:9]}};

assign tmp_fu_412_p3 = {{select_ln127_1_fu_392_p3}, {1'd0}};

assign trunc_ln130_1_fu_430_p1 = select_ln127_fu_378_p3[1:0];

assign trunc_ln130_2_fu_500_p1 = grp_fu_464_p2[2:0];

assign trunc_ln130_fu_400_p1 = select_ln127_1_fu_392_p3[1:0];

assign zext_ln128_fu_704_p1 = shl_ln135_1_fu_697_p3;

assign zext_ln130_1_fu_440_p1 = shl_ln130_fu_434_p2;

assign zext_ln130_5_fu_504_p1 = tmp_51_reg_890_pp0_iter8_reg;

assign zext_ln130_fu_420_p1 = tmp_fu_412_p3;

assign zext_ln131_fu_542_p1 = tmp_52_fu_532_p4;

assign zext_ln132_fu_635_p1 = tmp_53_fu_625_p4;

assign zext_ln133_fu_674_p1 = tmp_54_fu_664_p4;

assign zext_ln135_fu_816_p1 = add_ln135_fu_810_p2;

endmodule //bnn_top_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23
