-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bnn_top_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    WF1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    WF1_ce0 : OUT STD_LOGIC;
    WF1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    TAUF1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    TAUF1_ce0 : OUT STD_LOGIC;
    TAUF1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    f1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    f1_ce0 : OUT STD_LOGIC;
    f1_we0 : OUT STD_LOGIC;
    f1_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    l3_ce0 : OUT STD_LOGIC;
    l3_q0 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bnn_top_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln140_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln142_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln142_reg_367 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln145_1_fu_215_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln145_1_reg_377 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln142_1_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln142_1_reg_387 : STD_LOGIC_VECTOR (0 downto 0);
    signal f1_addr_reg_396 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln142_fu_210_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln145_fu_237_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln140_fu_200_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_11_fu_64 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal acc_fu_306_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_1_fu_68 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln142_fu_242_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal n_fu_72 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln140_2_fu_192_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten73_fu_76 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal add_ln140_fu_160_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal l3_ce0_local : STD_LOGIC;
    signal WF1_ce0_local : STD_LOGIC;
    signal TAUF1_ce0_local : STD_LOGIC;
    signal f1_we0_local : STD_LOGIC;
    signal icmp_ln148_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal f1_ce0_local : STD_LOGIC;
    signal add_ln140_1_fu_186_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln140_fu_178_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln145_fu_206_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_fu_219_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln4_fu_229_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln145_1_fu_279_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln145_fu_282_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_fu_288_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln146_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln146_fu_298_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln140_1_fu_272_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln6_fu_312_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln148_fu_320_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component bnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    acc_11_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    acc_11_fu_64 <= ap_const_lv12_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    acc_11_fu_64 <= acc_fu_306_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten73_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten73_fu_76 <= ap_const_lv18_0;
                elsif (((icmp_ln140_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten73_fu_76 <= add_ln140_fu_160_p2;
                end if;
            end if; 
        end if;
    end process;

    k_1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_1_fu_68 <= ap_const_lv11_0;
                elsif (((icmp_ln140_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    k_1_fu_68 <= add_ln142_fu_242_p2;
                end if;
            end if; 
        end if;
    end process;

    n_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_72 <= ap_const_lv8_0;
                elsif (((icmp_ln140_fu_154_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    n_fu_72 <= select_ln140_2_fu_192_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                f1_addr_reg_396 <= zext_ln140_fu_200_p1(7 - 1 downto 0);
                icmp_ln142_1_reg_387 <= icmp_ln142_1_fu_248_p2;
                icmp_ln142_reg_367 <= icmp_ln142_fu_172_p2;
                trunc_ln145_1_reg_377 <= trunc_ln145_1_fu_215_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    TAUF1_address0 <= zext_ln140_fu_200_p1(7 - 1 downto 0);
    TAUF1_ce0 <= TAUF1_ce0_local;

    TAUF1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            TAUF1_ce0_local <= ap_const_logic_1;
        else 
            TAUF1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    WF1_address0 <= zext_ln145_fu_237_p1(12 - 1 downto 0);
    WF1_ce0 <= WF1_ce0_local;

    WF1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            WF1_ce0_local <= ap_const_logic_1;
        else 
            WF1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_fu_306_p2 <= std_logic_vector(unsigned(select_ln146_fu_298_p3) + unsigned(select_ln140_1_fu_272_p3));
    add_ln140_1_fu_186_p2 <= std_logic_vector(unsigned(n_fu_72) + unsigned(ap_const_lv8_1));
    add_ln140_fu_160_p2 <= std_logic_vector(unsigned(indvar_flatten73_fu_76) + unsigned(ap_const_lv18_1));
    add_ln142_fu_242_p2 <= std_logic_vector(unsigned(select_ln140_fu_178_p3) + unsigned(ap_const_lv11_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln140_fu_154_p2)
    begin
        if (((icmp_ln140_fu_154_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    f1_address0 <= f1_addr_reg_396;
    f1_ce0 <= f1_ce0_local;

    f1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            f1_ce0_local <= ap_const_logic_1;
        else 
            f1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    f1_d0 <= icmp_ln148_fu_324_p2;
    f1_we0 <= f1_we0_local;

    f1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln142_1_reg_387)
    begin
        if (((icmp_ln142_1_reg_387 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            f1_we0_local <= ap_const_logic_1;
        else 
            f1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln140_fu_154_p2 <= "1" when (indvar_flatten73_fu_76 = ap_const_lv18_20000) else "0";
    icmp_ln142_1_fu_248_p2 <= "1" when (add_ln142_fu_242_p2 = ap_const_lv11_400) else "0";
    icmp_ln142_fu_172_p2 <= "1" when (k_1_fu_68 = ap_const_lv11_400) else "0";
    icmp_ln148_fu_324_p2 <= "1" when (signed(sext_ln148_fu_320_p1) > signed(TAUF1_q0)) else "0";
    l3_address0 <= zext_ln142_fu_210_p1(10 - 1 downto 0);
    l3_ce0 <= l3_ce0_local;

    l3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            l3_ce0_local <= ap_const_logic_1;
        else 
            l3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln145_fu_282_p2 <= std_logic_vector(shift_right(unsigned(WF1_q0),to_integer(unsigned('0' & zext_ln145_1_fu_279_p1(31-1 downto 0)))));
    lshr_ln4_fu_229_p3 <= (trunc_ln145_fu_206_p1 & tmp_s_fu_219_p4);
    select_ln140_1_fu_272_p3 <= 
        ap_const_lv12_0 when (icmp_ln142_reg_367(0) = '1') else 
        acc_11_fu_64;
    select_ln140_2_fu_192_p3 <= 
        add_ln140_1_fu_186_p2 when (icmp_ln142_fu_172_p2(0) = '1') else 
        n_fu_72;
    select_ln140_fu_178_p3 <= 
        ap_const_lv11_0 when (icmp_ln142_fu_172_p2(0) = '1') else 
        k_1_fu_68;
    select_ln146_fu_298_p3 <= 
        ap_const_lv12_FFF when (xor_ln146_fu_292_p2(0) = '1') else 
        ap_const_lv12_1;
        sext_ln148_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln6_fu_312_p3),32));

    shl_ln6_fu_312_p3 <= (acc_fu_306_p2 & ap_const_lv8_0);
    tmp_s_fu_219_p4 <= select_ln140_fu_178_p3(9 downto 5);
    trunc_ln145_1_fu_215_p1 <= select_ln140_fu_178_p3(5 - 1 downto 0);
    trunc_ln145_fu_206_p1 <= select_ln140_2_fu_192_p3(7 - 1 downto 0);
    w_fu_288_p1 <= lshr_ln145_fu_282_p2(1 - 1 downto 0);
    xor_ln146_fu_292_p2 <= (w_fu_288_p1 xor l3_q0);
    zext_ln140_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln140_2_fu_192_p3),64));
    zext_ln142_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln140_fu_178_p3),64));
    zext_ln145_1_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln145_1_reg_377),32));
    zext_ln145_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln4_fu_229_p3),64));
end behav;
