

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "42", "53", "62", "73", "82", "84", "95", "97"],
		"CDFG" : "bnn_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4145963", "EstimateLatencyMax" : "4145963",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "img_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "img_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "img_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "img_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "img_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "img_2", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "img_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "img_3", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "W1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "TAU1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "W2_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "W2_0", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "W2_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "W2_1", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "TAU2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "W3_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "W3_0", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "W3_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "W3_1", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "TAU3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "WF1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25_fu_561", "Port" : "WF1", "Inst_start_state" : "15", "Inst_end_state" : "19"}]},
			{"Name" : "TAUF1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25_fu_561", "Port" : "TAUF1", "Inst_start_state" : "15", "Inst_end_state" : "19"}]},
			{"Name" : "WF2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "95", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_153_26_fu_592", "Port" : "WF2", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "BF2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "logit0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "logit1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "pred_r", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "84", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "84", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "84", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "84", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "84", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_20", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_20", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_20", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_19", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_19", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_19", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_18", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_18", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_18", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_17", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_17", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_17", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_16", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_16", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_16", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_15", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_15", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_15", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_14", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_14", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_14", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_13", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_13", "Inst_start_state" : "9", "Inst_end_state" : "10"},
					{"ID" : "53", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_13", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "62", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "73", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Port" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7", "Inst_start_state" : "15", "Inst_end_state" : "16"}]},
			{"Name" : "f1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25_fu_561", "Port" : "f1", "Inst_start_state" : "15", "Inst_end_state" : "19"},
					{"ID" : "95", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_153_26_fu_592", "Port" : "f1", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "l3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25_fu_561", "Port" : "l3", "Inst_start_state" : "15", "Inst_end_state" : "19"},
					{"ID" : "84", "SubInstance" : "grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573", "Port" : "l3", "Inst_start_state" : "17", "Inst_end_state" : "18"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_49_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "22", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state10"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state11"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_78_8", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "22", "FirstState" : "ap_ST_fsm_state11", "LastState" : ["ap_ST_fsm_state14"], "QuitState" : ["ap_ST_fsm_state11"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state15"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_109_16", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "22", "FirstState" : "ap_ST_fsm_state15", "LastState" : ["ap_ST_fsm_state18"], "QuitState" : ["ap_ST_fsm_state15"], "PreState" : ["ap_ST_fsm_state11"], "PostState" : ["ap_ST_fsm_state19"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_20_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_19_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_18_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_17_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_16_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_15_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_14_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_13_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.f1_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l3_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384", "Parent" : "0", "Child" : ["25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2058", "EstimateLatencyMax" : "2058",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "img_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "img_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "img_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "img_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "W1_load_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_34", "Type" : "None", "Direction" : "I"},
			{"Name" : "W1_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_35", "Type" : "None", "Direction" : "I"},
			{"Name" : "W1_load_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_36", "Type" : "None", "Direction" : "I"},
			{"Name" : "W1_load_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_37", "Type" : "None", "Direction" : "I"},
			{"Name" : "cmp38_1_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "W1_load_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_38", "Type" : "None", "Direction" : "I"},
			{"Name" : "W1_load_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_39", "Type" : "None", "Direction" : "I"},
			{"Name" : "W1_load_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty_40", "Type" : "None", "Direction" : "I"},
			{"Name" : "W1_load_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_50_2_VITIS_LOOP_51_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter5", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter5", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.sparsemux_9_2_32_1_1_U1", "Parent" : "24"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.sparsemux_9_2_32_1_1_U2", "Parent" : "24"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.sparsemux_9_2_32_1_1_U3", "Parent" : "24"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U4", "Parent" : "24"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U5", "Parent" : "24"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U6", "Parent" : "24"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U7", "Parent" : "24"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.urem_7ns_4ns_3_11_1_U8", "Parent" : "24"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U9", "Parent" : "24"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U10", "Parent" : "24"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U11", "Parent" : "24"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.bitselect_1ns_32ns_5ns_1_1_1_U12", "Parent" : "24"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.mul_10ns_12ns_21_1_1_U13", "Parent" : "24"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.sparsemux_9_2_32_1_1_U14", "Parent" : "24"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.sparsemux_9_2_32_1_1_U15", "Parent" : "24"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.sparsemux_9_2_32_1_1_U16", "Parent" : "24"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3_fu_384.flow_control_loop_pipe_sequential_init_U", "Parent" : "24"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425", "Parent" : "0", "Child" : ["43", "44", "45", "46", "47", "48", "49", "50", "51", "52"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "270", "EstimateLatencyMax" : "270",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "TAU1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_13", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_65_6_VITIS_LOOP_66_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter13", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter13", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.mul_10ns_12ns_21_1_1_U49", "Parent" : "42"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.urem_7ns_4ns_3_11_1_U50", "Parent" : "42"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.mul_10ns_12ns_21_1_1_U51", "Parent" : "42"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.sparsemux_11_3_32_1_1_U52", "Parent" : "42"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.sparsemux_11_3_32_1_1_U53", "Parent" : "42"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.mul_10ns_12ns_21_1_1_U54", "Parent" : "42"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.mul_10ns_12ns_21_1_1_U55", "Parent" : "42"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.sparsemux_11_3_32_1_1_U56", "Parent" : "42"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.sparsemux_11_3_32_1_1_U57", "Parent" : "42"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_65_6_VITIS_LOOP_66_7_fu_425.flow_control_loop_pipe_sequential_init_U", "Parent" : "42"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458", "Parent" : "0", "Child" : ["54", "55", "56", "57", "58", "59", "60", "61"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40965", "EstimateLatencyMax" : "40965",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "mul_ln79", "Type" : "None", "Direction" : "I"},
			{"Name" : "W2_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "W2_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage4", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage4_subdone", "QuitState" : "ap_ST_fsm_pp0_stage4", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage4_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.sparsemux_17_3_1_1_1_U77", "Parent" : "53"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.sparsemux_17_3_1_1_1_U78", "Parent" : "53"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.sparsemux_17_3_1_1_1_U79", "Parent" : "53"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.urem_5ns_4ns_3_9_1_U80", "Parent" : "53"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.sparsemux_17_3_1_1_1_U81", "Parent" : "53"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.sparsemux_17_3_1_1_1_U82", "Parent" : "53"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.mul_8ns_10ns_17_1_1_U83", "Parent" : "53"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_79_9_VITIS_LOOP_80_10_VITIS_LOOP_82_11_fu_458.flow_control_loop_pipe_sequential_init_U", "Parent" : "53"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493", "Parent" : "0", "Child" : ["63", "64", "65", "66", "67", "68", "69", "70", "71", "72"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "76", "EstimateLatencyMax" : "76",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "shl_ln2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln104", "Type" : "None", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_96_14_VITIS_LOOP_97_15", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter11", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter11", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.urem_5ns_4ns_3_9_1_U105", "Parent" : "62"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.mul_8ns_10ns_17_1_1_U106", "Parent" : "62"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.mul_8ns_10ns_17_1_1_U107", "Parent" : "62"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.sparsemux_11_3_32_1_1_U108", "Parent" : "62"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.sparsemux_11_3_32_1_1_U109", "Parent" : "62"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.mul_8ns_10ns_17_1_1_U110", "Parent" : "62"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.mul_8ns_10ns_17_1_1_U111", "Parent" : "62"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.sparsemux_11_3_32_1_1_U112", "Parent" : "62"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.sparsemux_11_3_32_1_1_U113", "Parent" : "62"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15_fu_493.flow_control_loop_pipe_sequential_init_U", "Parent" : "62"},
	{"ID" : "73", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526", "Parent" : "0", "Child" : ["74", "75", "76", "77", "78", "79", "80", "81"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "20485", "EstimateLatencyMax" : "20485",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "mul_ln110", "Type" : "None", "Direction" : "I"},
			{"Name" : "W3_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "W3_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage4", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage4_subdone", "QuitState" : "ap_ST_fsm_pp0_stage4", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage4_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.sparsemux_17_3_1_1_1_U129", "Parent" : "73"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.sparsemux_17_3_1_1_1_U130", "Parent" : "73"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.sparsemux_17_3_1_1_1_U131", "Parent" : "73"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.mul_6ns_8ns_13_1_1_U132", "Parent" : "73"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.urem_5ns_4ns_3_9_1_U133", "Parent" : "73"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.sparsemux_17_3_1_1_1_U134", "Parent" : "73"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.sparsemux_17_3_1_1_1_U135", "Parent" : "73"},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_110_17_VITIS_LOOP_111_18_VITIS_LOOP_113_19_fu_526.flow_control_loop_pipe_sequential_init_U", "Parent" : "73"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25_fu_561", "Parent" : "0", "Child" : ["83"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "131074", "EstimateLatencyMax" : "131074",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "WF1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "TAUF1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "f1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "l3", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_140_24_VITIS_LOOP_142_25", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_140_24_VITIS_LOOP_142_25_fu_561.flow_control_loop_pipe_sequential_init_U", "Parent" : "82"},
	{"ID" : "84", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573", "Parent" : "0", "Child" : ["85", "86", "87", "88", "89", "90", "91", "92", "93", "94"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "28", "EstimateLatencyMax" : "28",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "sext_ln135", "Type" : "None", "Direction" : "I"},
			{"Name" : "oc_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "l3", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_127_22_VITIS_LOOP_128_23", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter11", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter11", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "85", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.urem_5ns_4ns_3_9_1_U153", "Parent" : "84"},
	{"ID" : "86", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.mul_6ns_8ns_13_1_1_U154", "Parent" : "84"},
	{"ID" : "87", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.sparsemux_11_3_32_1_1_U155", "Parent" : "84"},
	{"ID" : "88", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.sparsemux_11_3_32_1_1_U156", "Parent" : "84"},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.mul_6ns_8ns_13_1_1_U157", "Parent" : "84"},
	{"ID" : "90", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.mul_6ns_8ns_13_1_1_U158", "Parent" : "84"},
	{"ID" : "91", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.sparsemux_11_3_32_1_1_U159", "Parent" : "84"},
	{"ID" : "92", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.sparsemux_11_3_32_1_1_x_U160", "Parent" : "84"},
	{"ID" : "93", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.am_addmul_5ns_5ns_7ns_13_4_1_U161", "Parent" : "84"},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23_fu_573.flow_control_loop_pipe_sequential_init_U", "Parent" : "84"},
	{"ID" : "95", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_153_26_fu_592", "Parent" : "0", "Child" : ["96"],
		"CDFG" : "bnn_top_Pipeline_VITIS_LOOP_153_26",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "130", "EstimateLatencyMax" : "130",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "sext_ln152_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln152", "Type" : "None", "Direction" : "I"},
			{"Name" : "WF2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "a1_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "a0_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "f1", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_153_26", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "96", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_VITIS_LOOP_153_26_fu_592.flow_control_loop_pipe_sequential_init_U", "Parent" : "95"},
	{"ID" : "97", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bitselect_1ns_32ns_5ns_1_1_1_U182", "Parent" : "0"}]}
