-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bnn_top_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    shl_ln2 : IN STD_LOGIC_VECTOR (8 downto 0);
    sext_ln104 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bnn_top_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv17_19A : STD_LOGIC_VECTOR (16 downto 0) := "00000000110011010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln96_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln104_cast_fu_443_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln104_cast_reg_988 : STD_LOGIC_VECTOR (39 downto 0);
    signal select_ln96_1_fu_503_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_1_reg_997_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln99_fu_511_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_reg_1003_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_fu_525_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln97_reg_1011_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln99_fu_539_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln99_reg_1018_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln99_1_fu_590_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_1_reg_1024 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_1_reg_1024_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln99_1_reg_1024_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal m_1_fu_833_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_1_reg_1132 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln99_4_fu_647_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln100_fu_686_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln101_fu_779_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln102_fu_818_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln104_fu_849_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal pw_fu_110 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln97_fu_569_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_pw_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ph_fu_114 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_sig_allocacmp_ph_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten36_fu_118 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln96_fu_471_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten36_load : STD_LOGIC_VECTOR (6 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local : STD_LOGIC;
    signal icmp_ln104_fu_949_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local : STD_LOGIC;
    signal icmp_ln97_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln96_1_fu_497_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln99_fu_515_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln96_fu_489_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln99_1_fu_529_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln99_1_fu_535_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln99_fu_521_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_545_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_545_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_545_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_604_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_fu_597_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln99_3_fu_611_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln99_2_fu_594_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln99_fu_615_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln99_1_fu_621_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln99_fu_631_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln99_fu_631_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln99_fu_631_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_1_fu_637_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln4_fu_656_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln100_fu_670_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln100_fu_670_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln100_fu_670_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_fu_676_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal s0_fu_695_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal s1_fu_722_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln5_fu_749_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln101_fu_763_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln101_fu_763_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln101_fu_763_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_769_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln6_fu_788_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln102_fu_802_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln102_fu_802_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln102_fu_802_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_4_fu_808_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal s1_fu_722_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal s0_fu_695_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln103_fu_827_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln96_fu_841_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln104_fu_844_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal s2_fu_861_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal s3_fu_888_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal s2_fu_861_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln103_1_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal s3_fu_888_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_3_fu_920_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln103_2_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln103_fu_933_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln104_1_fu_941_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln100_fu_670_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln101_fu_763_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln102_fu_802_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln99_fu_631_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal s0_fu_695_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_695_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_695_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_695_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_695_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_722_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_722_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_722_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_722_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_722_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_861_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_861_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_861_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_861_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_861_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_888_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_888_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_888_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_888_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_888_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component bnn_top_urem_5ns_4ns_3_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component bnn_top_mul_8ns_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component bnn_top_sparsemux_11_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_5ns_4ns_3_9_1_U105 : component bnn_top_urem_5ns_4ns_3_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 4,
        dout_WIDTH => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_545_p0,
        din1 => grp_fu_545_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_545_p2);

    mul_8ns_10ns_17_1_1_U106 : component bnn_top_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln99_fu_631_p0,
        din1 => mul_ln99_fu_631_p1,
        dout => mul_ln99_fu_631_p2);

    mul_8ns_10ns_17_1_1_U107 : component bnn_top_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln100_fu_670_p0,
        din1 => mul_ln100_fu_670_p1,
        dout => mul_ln100_fu_670_p2);

    sparsemux_11_3_32_1_1_U108 : component bnn_top_sparsemux_11_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1,
        def => s0_fu_695_p11,
        sel => trunc_ln99_1_reg_1024_pp0_iter9_reg,
        dout => s0_fu_695_p13);

    sparsemux_11_3_32_1_1_U109 : component bnn_top_sparsemux_11_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 32,
        CASE1 => "000",
        din1_WIDTH => 32,
        CASE2 => "001",
        din2_WIDTH => 32,
        CASE3 => "010",
        din3_WIDTH => 32,
        CASE4 => "011",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1,
        def => s1_fu_722_p11,
        sel => trunc_ln99_1_reg_1024_pp0_iter9_reg,
        dout => s1_fu_722_p13);

    mul_8ns_10ns_17_1_1_U110 : component bnn_top_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln101_fu_763_p0,
        din1 => mul_ln101_fu_763_p1,
        dout => mul_ln101_fu_763_p2);

    mul_8ns_10ns_17_1_1_U111 : component bnn_top_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln102_fu_802_p0,
        din1 => mul_ln102_fu_802_p1,
        dout => mul_ln102_fu_802_p2);

    sparsemux_11_3_32_1_1_U112 : component bnn_top_sparsemux_11_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 32,
        CASE1 => "000",
        din1_WIDTH => 32,
        CASE2 => "001",
        din2_WIDTH => 32,
        CASE3 => "010",
        din3_WIDTH => 32,
        CASE4 => "011",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0,
        def => s2_fu_861_p11,
        sel => trunc_ln99_1_reg_1024_pp0_iter10_reg,
        dout => s2_fu_861_p13);

    sparsemux_11_3_32_1_1_U113 : component bnn_top_sparsemux_11_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "011",
        din0_WIDTH => 32,
        CASE1 => "100",
        din1_WIDTH => 32,
        CASE2 => "000",
        din2_WIDTH => 32,
        CASE3 => "001",
        din3_WIDTH => 32,
        CASE4 => "010",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0,
        def => s3_fu_888_p11,
        sel => trunc_ln99_1_reg_1024_pp0_iter10_reg,
        dout => s3_fu_888_p13);

    flow_control_loop_pipe_sequential_init_U : component bnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten36_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln96_fu_465_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten36_fu_118 <= add_ln96_fu_471_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten36_fu_118 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    ph_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln96_fu_465_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ph_fu_114 <= select_ln96_1_fu_503_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ph_fu_114 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    pw_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln96_fu_465_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    pw_fu_110 <= add_ln97_fu_569_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    pw_fu_110 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln99_reg_1018 <= add_ln99_fu_539_p2;
                add_ln99_reg_1018_pp0_iter1_reg <= add_ln99_reg_1018;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln96_1_reg_997 <= select_ln96_1_fu_503_p3;
                select_ln96_1_reg_997_pp0_iter1_reg <= select_ln96_1_reg_997;
                sext_ln104_cast_reg_988 <= sext_ln104_cast_fu_443_p1;
                trunc_ln97_reg_1011 <= trunc_ln97_fu_525_p1;
                trunc_ln97_reg_1011_pp0_iter1_reg <= trunc_ln97_reg_1011;
                trunc_ln99_reg_1003 <= trunc_ln99_fu_511_p1;
                trunc_ln99_reg_1003_pp0_iter1_reg <= trunc_ln99_reg_1003;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln99_reg_1018_pp0_iter2_reg <= add_ln99_reg_1018_pp0_iter1_reg;
                add_ln99_reg_1018_pp0_iter3_reg <= add_ln99_reg_1018_pp0_iter2_reg;
                add_ln99_reg_1018_pp0_iter4_reg <= add_ln99_reg_1018_pp0_iter3_reg;
                add_ln99_reg_1018_pp0_iter5_reg <= add_ln99_reg_1018_pp0_iter4_reg;
                add_ln99_reg_1018_pp0_iter6_reg <= add_ln99_reg_1018_pp0_iter5_reg;
                add_ln99_reg_1018_pp0_iter7_reg <= add_ln99_reg_1018_pp0_iter6_reg;
                add_ln99_reg_1018_pp0_iter8_reg <= add_ln99_reg_1018_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                m_1_reg_1132 <= m_1_fu_833_p3;
                select_ln96_1_reg_997_pp0_iter10_reg <= select_ln96_1_reg_997_pp0_iter9_reg;
                select_ln96_1_reg_997_pp0_iter2_reg <= select_ln96_1_reg_997_pp0_iter1_reg;
                select_ln96_1_reg_997_pp0_iter3_reg <= select_ln96_1_reg_997_pp0_iter2_reg;
                select_ln96_1_reg_997_pp0_iter4_reg <= select_ln96_1_reg_997_pp0_iter3_reg;
                select_ln96_1_reg_997_pp0_iter5_reg <= select_ln96_1_reg_997_pp0_iter4_reg;
                select_ln96_1_reg_997_pp0_iter6_reg <= select_ln96_1_reg_997_pp0_iter5_reg;
                select_ln96_1_reg_997_pp0_iter7_reg <= select_ln96_1_reg_997_pp0_iter6_reg;
                select_ln96_1_reg_997_pp0_iter8_reg <= select_ln96_1_reg_997_pp0_iter7_reg;
                select_ln96_1_reg_997_pp0_iter9_reg <= select_ln96_1_reg_997_pp0_iter8_reg;
                trunc_ln97_reg_1011_pp0_iter10_reg <= trunc_ln97_reg_1011_pp0_iter9_reg;
                trunc_ln97_reg_1011_pp0_iter2_reg <= trunc_ln97_reg_1011_pp0_iter1_reg;
                trunc_ln97_reg_1011_pp0_iter3_reg <= trunc_ln97_reg_1011_pp0_iter2_reg;
                trunc_ln97_reg_1011_pp0_iter4_reg <= trunc_ln97_reg_1011_pp0_iter3_reg;
                trunc_ln97_reg_1011_pp0_iter5_reg <= trunc_ln97_reg_1011_pp0_iter4_reg;
                trunc_ln97_reg_1011_pp0_iter6_reg <= trunc_ln97_reg_1011_pp0_iter5_reg;
                trunc_ln97_reg_1011_pp0_iter7_reg <= trunc_ln97_reg_1011_pp0_iter6_reg;
                trunc_ln97_reg_1011_pp0_iter8_reg <= trunc_ln97_reg_1011_pp0_iter7_reg;
                trunc_ln97_reg_1011_pp0_iter9_reg <= trunc_ln97_reg_1011_pp0_iter8_reg;
                trunc_ln99_1_reg_1024 <= trunc_ln99_1_fu_590_p1;
                trunc_ln99_1_reg_1024_pp0_iter10_reg <= trunc_ln99_1_reg_1024_pp0_iter9_reg;
                trunc_ln99_1_reg_1024_pp0_iter9_reg <= trunc_ln99_1_reg_1024;
                trunc_ln99_reg_1003_pp0_iter2_reg <= trunc_ln99_reg_1003_pp0_iter1_reg;
                trunc_ln99_reg_1003_pp0_iter3_reg <= trunc_ln99_reg_1003_pp0_iter2_reg;
                trunc_ln99_reg_1003_pp0_iter4_reg <= trunc_ln99_reg_1003_pp0_iter3_reg;
                trunc_ln99_reg_1003_pp0_iter5_reg <= trunc_ln99_reg_1003_pp0_iter4_reg;
                trunc_ln99_reg_1003_pp0_iter6_reg <= trunc_ln99_reg_1003_pp0_iter5_reg;
                trunc_ln99_reg_1003_pp0_iter7_reg <= trunc_ln99_reg_1003_pp0_iter6_reg;
                trunc_ln99_reg_1003_pp0_iter8_reg <= trunc_ln99_reg_1003_pp0_iter7_reg;
                trunc_ln99_reg_1003_pp0_iter9_reg <= trunc_ln99_reg_1003_pp0_iter8_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln104_fu_844_p2 <= std_logic_vector(unsigned(zext_ln96_fu_841_p1) + unsigned(shl_ln2));
    add_ln4_fu_656_p5 <= (((trunc_ln99_reg_1003_pp0_iter8_reg & ap_const_lv1_0) & trunc_ln97_reg_1011_pp0_iter8_reg) & ap_const_lv1_1);
    add_ln5_fu_749_p5 <= (((trunc_ln99_reg_1003_pp0_iter9_reg & ap_const_lv1_1) & trunc_ln97_reg_1011_pp0_iter9_reg) & ap_const_lv1_0);
    add_ln6_fu_788_p5 <= (((trunc_ln99_reg_1003_pp0_iter9_reg & ap_const_lv1_1) & trunc_ln97_reg_1011_pp0_iter9_reg) & ap_const_lv1_1);
    add_ln96_1_fu_497_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ph_load) + unsigned(ap_const_lv4_1));
    add_ln96_fu_471_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten36_load) + unsigned(ap_const_lv7_1));
    add_ln97_fu_569_p2 <= std_logic_vector(unsigned(select_ln96_fu_489_p3) + unsigned(ap_const_lv4_1));
    add_ln99_1_fu_621_p2 <= std_logic_vector(unsigned(zext_ln99_2_fu_594_p1) + unsigned(sub_ln99_fu_615_p2));
    add_ln99_fu_539_p2 <= std_logic_vector(unsigned(zext_ln99_1_fu_535_p1) + unsigned(zext_ln99_fu_521_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln96_fu_465_p2)
    begin
        if (((icmp_ln96_fu_465_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten36_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten36_fu_118)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten36_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten36_load <= indvar_flatten36_fu_118;
        end if; 
    end process;


    ap_sig_allocacmp_ph_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ph_fu_114)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ph_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_ph_load <= ph_fu_114;
        end if; 
    end process;


    ap_sig_allocacmp_pw_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, pw_fu_110, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_pw_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_pw_load <= pw_fu_110;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_4))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_3))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_0))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln99_1_reg_1024_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln101_fu_779_p1, zext_ln102_fu_818_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= zext_ln102_fu_818_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= zext_ln101_fu_779_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln99_1_reg_1024, zext_ln99_4_fu_647_p1, ap_block_pp0_stage0, zext_ln100_fu_686_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024 = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= zext_ln100_fu_686_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024 = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= zext_ln99_4_fu_647_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_1)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_2)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln99_1_reg_1024_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln101_fu_779_p1, zext_ln102_fu_818_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= zext_ln102_fu_818_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= zext_ln101_fu_779_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln99_1_reg_1024, zext_ln99_4_fu_647_p1, ap_block_pp0_stage0, zext_ln100_fu_686_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024 = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= zext_ln100_fu_686_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024 = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= zext_ln99_4_fu_647_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_0)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_1)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln99_1_reg_1024_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln101_fu_779_p1, zext_ln102_fu_818_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= zext_ln102_fu_818_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= zext_ln101_fu_779_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln99_1_reg_1024, zext_ln99_4_fu_647_p1, ap_block_pp0_stage0, zext_ln100_fu_686_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024 = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= zext_ln100_fu_686_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024 = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= zext_ln99_4_fu_647_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_4)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_0)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln99_1_reg_1024_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln101_fu_779_p1, zext_ln102_fu_818_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= zext_ln102_fu_818_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= zext_ln101_fu_779_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln99_1_reg_1024, zext_ln99_4_fu_647_p1, ap_block_pp0_stage0, zext_ln100_fu_686_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024 = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= zext_ln100_fu_686_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024 = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= zext_ln99_4_fu_647_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_4)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_0)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_2))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_7))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_6))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_address0 <= zext_ln104_fu_849_p1(9 - 1 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_d0 <= icmp_ln104_fu_949_p2;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln97_reg_1011_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln97_reg_1011_pp0_iter10_reg = ap_const_lv3_5))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln99_1_reg_1024_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln101_fu_779_p1, zext_ln102_fu_818_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= zext_ln102_fu_818_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= zext_ln101_fu_779_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln99_1_reg_1024, zext_ln99_4_fu_647_p1, ap_block_pp0_stage0, zext_ln100_fu_686_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln99_1_reg_1024 = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= zext_ln100_fu_686_p1(8 - 1 downto 0);
            elsif ((trunc_ln99_1_reg_1024 = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= zext_ln99_4_fu_647_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln99_1_reg_1024_pp0_iter9_reg = ap_const_lv3_2)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln99_1_reg_1024)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln99_1_reg_1024 = ap_const_lv3_3)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_545_p0 <= std_logic_vector(unsigned(zext_ln99_1_fu_535_p1) + unsigned(zext_ln99_fu_521_p1));
    grp_fu_545_p1 <= ap_const_lv5_5(4 - 1 downto 0);
    icmp_ln103_1_fu_915_p2 <= "1" when (signed(s2_fu_861_p13) > signed(m_1_reg_1132)) else "0";
    icmp_ln103_2_fu_927_p2 <= "1" when (signed(s3_fu_888_p13) > signed(m_3_fu_920_p3)) else "0";
    icmp_ln103_fu_827_p2 <= "1" when (signed(s1_fu_722_p13) > signed(s0_fu_695_p13)) else "0";
    icmp_ln104_fu_949_p2 <= "1" when (signed(shl_ln104_1_fu_941_p3) > signed(sext_ln104_cast_reg_988)) else "0";
    icmp_ln96_fu_465_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten36_load = ap_const_lv7_40) else "0";
    icmp_ln97_fu_483_p2 <= "1" when (ap_sig_allocacmp_pw_load = ap_const_lv4_8) else "0";
    m_1_fu_833_p3 <= 
        s1_fu_722_p13 when (icmp_ln103_fu_827_p2(0) = '1') else 
        s0_fu_695_p13;
    m_3_fu_920_p3 <= 
        s2_fu_861_p13 when (icmp_ln103_1_fu_915_p2(0) = '1') else 
        m_1_reg_1132;
    mul_ln100_fu_670_p0 <= mul_ln100_fu_670_p00(8 - 1 downto 0);
    mul_ln100_fu_670_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln4_fu_656_p5),17));
    mul_ln100_fu_670_p1 <= ap_const_lv17_19A(10 - 1 downto 0);
    mul_ln101_fu_763_p0 <= mul_ln101_fu_763_p00(8 - 1 downto 0);
    mul_ln101_fu_763_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln5_fu_749_p5),17));
    mul_ln101_fu_763_p1 <= ap_const_lv17_19A(10 - 1 downto 0);
    mul_ln102_fu_802_p0 <= mul_ln102_fu_802_p00(8 - 1 downto 0);
    mul_ln102_fu_802_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln6_fu_788_p5),17));
    mul_ln102_fu_802_p1 <= ap_const_lv17_19A(10 - 1 downto 0);
    mul_ln99_fu_631_p0 <= mul_ln99_fu_631_p00(8 - 1 downto 0);
    mul_ln99_fu_631_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln99_1_fu_621_p2),17));
    mul_ln99_fu_631_p1 <= ap_const_lv17_19A(10 - 1 downto 0);
    p_shl_fu_597_p3 <= (trunc_ln99_reg_1003_pp0_iter8_reg & ap_const_lv5_0);
    s0_fu_695_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    s1_fu_722_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    s2_fu_861_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    s3_fu_888_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    select_ln103_fu_933_p3 <= 
        s3_fu_888_p13 when (icmp_ln103_2_fu_927_p2(0) = '1') else 
        m_3_fu_920_p3;
    select_ln96_1_fu_503_p3 <= 
        add_ln96_1_fu_497_p2 when (icmp_ln97_fu_483_p2(0) = '1') else 
        ap_sig_allocacmp_ph_load;
    select_ln96_fu_489_p3 <= 
        ap_const_lv4_0 when (icmp_ln97_fu_483_p2(0) = '1') else 
        ap_sig_allocacmp_pw_load;
        sext_ln104_cast_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln104),40));

    shl_ln104_1_fu_941_p3 <= (select_ln103_fu_933_p3 & ap_const_lv8_0);
    shl_ln99_1_fu_529_p2 <= std_logic_vector(shift_left(unsigned(select_ln96_fu_489_p3),to_integer(unsigned('0' & ap_const_lv4_1(4-1 downto 0)))));
    shl_ln99_fu_515_p2 <= std_logic_vector(shift_left(unsigned(select_ln96_1_fu_503_p3),to_integer(unsigned('0' & ap_const_lv4_1(4-1 downto 0)))));
    sub_ln99_fu_615_p2 <= std_logic_vector(unsigned(p_shl_fu_597_p3) - unsigned(zext_ln99_3_fu_611_p1));
    tmp_1_fu_637_p4 <= mul_ln99_fu_631_p2(16 downto 11);
    tmp_2_fu_676_p4 <= mul_ln100_fu_670_p2(16 downto 11);
    tmp_3_fu_769_p4 <= mul_ln101_fu_763_p2(16 downto 11);
    tmp_4_fu_808_p4 <= mul_ln102_fu_802_p2(16 downto 11);
    tmp_fu_604_p3 <= (select_ln96_1_reg_997_pp0_iter8_reg & ap_const_lv1_0);
    trunc_ln97_fu_525_p1 <= select_ln96_fu_489_p3(3 - 1 downto 0);
    trunc_ln99_1_fu_590_p1 <= grp_fu_545_p2(3 - 1 downto 0);
    trunc_ln99_fu_511_p1 <= select_ln96_1_fu_503_p3(3 - 1 downto 0);
    zext_ln100_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_676_p4),64));
    zext_ln101_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_769_p4),64));
    zext_ln102_fu_818_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_808_p4),64));
    zext_ln104_fu_849_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln104_fu_844_p2),64));
    zext_ln96_fu_841_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln96_1_reg_997_pp0_iter10_reg),9));
    zext_ln99_1_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln99_1_fu_529_p2),5));
    zext_ln99_2_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln99_reg_1018_pp0_iter8_reg),8));
    zext_ln99_3_fu_611_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_604_p3),8));
    zext_ln99_4_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_637_p4),64));
    zext_ln99_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln99_fu_515_p2),5));
end behav;
