-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity hdr_top_TAU1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 18; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of hdr_top_TAU1_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "101111000010110111", 1 => "110110011100111010", 2 => "000011001111101101", 3 => "000001111011100101", 
    4 => "111111010001001001", 5 => "000100101001010111", 6 => "000010111100111100", 7 => "000100001000011000", 
    8 => "001010111100110001", 9 => "000011010100101101", 10 => "000100010111011110", 11 => "111111100111110000", 
    12 => "000100110100011001", 13 => "111110101011101000", 14 => "000011010111000111", 15 => "110111111010100000", 
    16 => "000101000001001010", 17 => "000010111011000001", 18 => "000000101111010001", 19 => "000000101111110011", 
    20 => "111101101011000101", 21 => "000011110011111100", 22 => "111101110100110000", 23 => "000011101101101001", 
    24 => "000001000111100111", 25 => "000000100111011100", 26 => "110001000111110010", 27 => "000001011011011001", 
    28 => "001011011100001110", 29 => "111111111011111100", 30 => "000100010011111001", 31 => "000011001110101000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

