[hls]
relative_roots=D:/CodeWSL/Camera_AI/hls
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_50_2  
syn.directive.array_partition=bnn_top/bnn_top(int const*, unsigned int const*, int const*, unsigned int const*, int const*, unsigned int const*, int const*, unsigned int const*, int const*, int const*, int const*, int&, int&, int&)::ps dim=1 type=cyclic factor=5 variable=bnn_top(int const*, unsigned int const*, int const*, unsigned int const*, int const*, unsigned int const*, int const*, unsigned int const*, int const*, int const*, int const*, int&, int&, int&)::ps
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_65_6  
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_80_10  
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_79_9  
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_96_14  
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_111_18  
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_110_17  
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_127_22  
syn.directive.loop_flatten=bnn_top/VITIS_LOOP_140_24  


