// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module bnn_top_bnn_top_Pipeline_VITIS_LOOP_153_26 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln152_1,
        sext_ln152,
        WF2_address0,
        WF2_ce0,
        WF2_q0,
        WF2_address1,
        WF2_ce1,
        WF2_q1,
        a1_1_out,
        a1_1_out_ap_vld,
        a0_1_out,
        a0_1_out_ap_vld,
        f1_address0,
        f1_ce0,
        f1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sext_ln152_1;
input  [31:0] sext_ln152;
output  [7:0] WF2_address0;
output   WF2_ce0;
input  [31:0] WF2_q0;
output  [7:0] WF2_address1;
output   WF2_ce1;
input  [31:0] WF2_q1;
output  [39:0] a1_1_out;
output   a1_1_out_ap_vld;
output  [39:0] a0_1_out;
output   a0_1_out_ap_vld;
output  [6:0] f1_address0;
output   f1_ce0;
input  [0:0] f1_q0;

reg ap_idle;
reg a1_1_out_ap_vld;
reg a0_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln153_fu_154_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln153_fu_166_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln156_fu_184_p1;
reg   [39:0] a0_fu_52;
wire   [39:0] a0_1_fu_226_p2;
wire  signed [39:0] sext_ln152_cast_fu_128_p1;
wire    ap_loop_init;
reg   [39:0] a1_fu_56;
wire   [39:0] a1_1_fu_250_p2;
wire  signed [39:0] sext_ln152_1_cast_fu_132_p1;
reg   [7:0] k_fu_60;
wire   [7:0] add_ln153_fu_160_p2;
reg   [7:0] ap_sig_allocacmp_k_1;
wire    ap_block_pp0_stage0_01001;
reg    WF2_ce1_local;
reg    WF2_ce0_local;
reg    f1_ce0_local;
wire   [6:0] trunc_ln156_fu_172_p1;
wire   [7:0] zext_ln156_cast_fu_176_p3;
wire  signed [32:0] sext_ln155_fu_200_p1;
wire   [32:0] sub_ln157_fu_208_p2;
wire   [32:0] select_ln157_fu_214_p3;
wire  signed [39:0] sext_ln157_fu_222_p1;
wire  signed [32:0] sext_ln156_fu_204_p1;
wire   [32:0] sub_ln158_fu_232_p2;
wire   [32:0] select_ln158_fu_238_p3;
wire  signed [39:0] sext_ln158_fu_246_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 a0_fu_52 = 40'd0;
#0 a1_fu_56 = 40'd0;
#0 k_fu_60 = 8'd0;
#0 ap_done_reg = 1'b0;
end

bnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            a0_fu_52 <= sext_ln152_cast_fu_128_p1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            a0_fu_52 <= a0_1_fu_226_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            a1_fu_56 <= sext_ln152_1_cast_fu_132_p1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            a1_fu_56 <= a1_1_fu_250_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_60 <= add_ln153_fu_160_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_60 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        WF2_ce0_local = 1'b1;
    end else begin
        WF2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        WF2_ce1_local = 1'b1;
    end else begin
        WF2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a0_1_out_ap_vld = 1'b1;
    end else begin
        a0_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln153_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a1_1_out_ap_vld = 1'b1;
    end else begin
        a1_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln153_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        f1_ce0_local = 1'b1;
    end else begin
        f1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign WF2_address0 = zext_ln156_fu_184_p1;

assign WF2_address1 = zext_ln153_fu_166_p1;

assign WF2_ce0 = WF2_ce0_local;

assign WF2_ce1 = WF2_ce1_local;

assign a0_1_fu_226_p2 = ($signed(sext_ln157_fu_222_p1) + $signed(a0_fu_52));

assign a0_1_out = a0_fu_52;

assign a1_1_fu_250_p2 = ($signed(sext_ln158_fu_246_p1) + $signed(a1_fu_56));

assign a1_1_out = a1_fu_56;

assign add_ln153_fu_160_p2 = (ap_sig_allocacmp_k_1 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign f1_address0 = zext_ln153_fu_166_p1;

assign f1_ce0 = f1_ce0_local;

assign icmp_ln153_fu_154_p2 = ((ap_sig_allocacmp_k_1 == 8'd128) ? 1'b1 : 1'b0);

assign select_ln157_fu_214_p3 = ((f1_q0[0:0] == 1'b1) ? sext_ln155_fu_200_p1 : sub_ln157_fu_208_p2);

assign select_ln158_fu_238_p3 = ((f1_q0[0:0] == 1'b1) ? sext_ln156_fu_204_p1 : sub_ln158_fu_232_p2);

assign sext_ln152_1_cast_fu_132_p1 = $signed(sext_ln152_1);

assign sext_ln152_cast_fu_128_p1 = $signed(sext_ln152);

assign sext_ln155_fu_200_p1 = $signed(WF2_q1);

assign sext_ln156_fu_204_p1 = $signed(WF2_q0);

assign sext_ln157_fu_222_p1 = $signed(select_ln157_fu_214_p3);

assign sext_ln158_fu_246_p1 = $signed(select_ln158_fu_238_p3);

assign sub_ln157_fu_208_p2 = ($signed(33'd0) - $signed(sext_ln155_fu_200_p1));

assign sub_ln158_fu_232_p2 = ($signed(33'd0) - $signed(sext_ln156_fu_204_p1));

assign trunc_ln156_fu_172_p1 = ap_sig_allocacmp_k_1[6:0];

assign zext_ln153_fu_166_p1 = ap_sig_allocacmp_k_1;

assign zext_ln156_cast_fu_176_p3 = {{1'd1}, {trunc_ln156_fu_172_p1}};

assign zext_ln156_fu_184_p1 = zext_ln156_cast_fu_176_p3;

endmodule //bnn_top_bnn_top_Pipeline_VITIS_LOOP_153_26
