-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bnn_top_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln135 : IN STD_LOGIC_VECTOR (31 downto 0);
    oc_2 : IN STD_LOGIC_VECTOR (5 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1 : OUT STD_LOGIC;
    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    l3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    l3_ce0 : OUT STD_LOGIC;
    l3_we0 : OUT STD_LOGIC;
    l3_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bnn_top_bnn_top_Pipeline_VITIS_LOOP_127_22_VITIS_LOOP_128_23 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv13_67 : STD_LOGIC_VECTOR (12 downto 0) := "0000001100111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln127_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln135_cast_fu_332_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln135_cast_reg_856 : STD_LOGIC_VECTOR (39 downto 0);
    signal select_ln127_fu_378_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter7_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter8_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln127_reg_865_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln130_fu_400_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_reg_870_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_fu_430_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln130_1_reg_878_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln130_fu_444_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_51_reg_890 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_51_reg_890_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_51_reg_890_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_51_reg_890_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_51_reg_890_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_51_reg_890_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln130_2_fu_500_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln130_2_reg_895 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln130_2_reg_895_pp0_iter9_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln130_2_reg_895_pp0_iter10_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal m_9_fu_689_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_9_reg_1003 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln130_5_fu_504_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln131_fu_542_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln132_fu_635_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln133_fu_674_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln135_fu_816_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal pw_fu_90 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln128_fu_470_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_pw_load : STD_LOGIC_VECTOR (2 downto 0);
    signal ph_fu_94 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln127_1_fu_392_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_ph_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten66_fu_98 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln127_fu_360_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten66_load : STD_LOGIC_VECTOR (4 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local : STD_LOGIC;
    signal bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal l3_we0_local : STD_LOGIC;
    signal icmp_ln135_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal l3_ce0_local : STD_LOGIC;
    signal icmp_ln128_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln127_1_fu_386_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_412_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_fu_404_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln130_fu_420_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln130_fu_434_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln130_1_fu_440_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln130_fu_424_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln130_2_fu_454_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_464_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_51_fu_491_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_821_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_464_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln7_fu_512_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln131_fu_526_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln131_fu_526_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln131_fu_526_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_52_fu_532_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal s0_fu_551_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal s1_fu_578_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln8_fu_605_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln132_fu_619_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln132_fu_619_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln132_fu_619_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_53_fu_625_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln9_fu_644_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln133_fu_658_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln133_fu_658_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln133_fu_658_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_54_fu_664_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal s1_fu_578_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal s0_fu_551_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln134_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln135_1_fu_697_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal s2_fu_708_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal s3_fu_735_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal s2_fu_708_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln134_1_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal s3_fu_735_p13 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_11_fu_767_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln134_2_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln134_fu_780_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_788_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp12_fu_802_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln128_fu_704_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln135_fu_810_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_821_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_821_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_821_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_821_p00 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_821_p10 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln131_fu_526_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln132_fu_619_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln133_fu_658_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal s0_fu_551_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_551_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_551_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_551_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_fu_551_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_578_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_578_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_578_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_578_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_fu_578_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_708_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_708_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_708_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_708_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s2_fu_708_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_735_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_735_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_735_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_735_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_fu_735_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component bnn_top_urem_5ns_4ns_3_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component bnn_top_mul_6ns_8ns_13_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component bnn_top_sparsemux_11_3_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bnn_top_sparsemux_11_3_32_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bnn_top_am_addmul_5ns_5ns_7ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component bnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_5ns_4ns_3_9_1_U153 : component bnn_top_urem_5ns_4ns_3_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 4,
        dout_WIDTH => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_ln130_fu_444_p2,
        din1 => grp_fu_464_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_464_p2);

    mul_6ns_8ns_13_1_1_U154 : component bnn_top_mul_6ns_8ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln131_fu_526_p0,
        din1 => mul_ln131_fu_526_p1,
        dout => mul_ln131_fu_526_p2);

    sparsemux_11_3_32_1_1_U155 : component bnn_top_sparsemux_11_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 32,
        CASE1 => "001",
        din1_WIDTH => 32,
        CASE2 => "010",
        din2_WIDTH => 32,
        CASE3 => "011",
        din3_WIDTH => 32,
        CASE4 => "100",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1,
        def => s0_fu_551_p11,
        sel => trunc_ln130_2_reg_895_pp0_iter9_reg,
        dout => s0_fu_551_p13);

    sparsemux_11_3_32_1_1_U156 : component bnn_top_sparsemux_11_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 32,
        CASE1 => "000",
        din1_WIDTH => 32,
        CASE2 => "001",
        din2_WIDTH => 32,
        CASE3 => "010",
        din3_WIDTH => 32,
        CASE4 => "011",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1,
        def => s1_fu_578_p11,
        sel => trunc_ln130_2_reg_895_pp0_iter9_reg,
        dout => s1_fu_578_p13);

    mul_6ns_8ns_13_1_1_U157 : component bnn_top_mul_6ns_8ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln132_fu_619_p0,
        din1 => mul_ln132_fu_619_p1,
        dout => mul_ln132_fu_619_p2);

    mul_6ns_8ns_13_1_1_U158 : component bnn_top_mul_6ns_8ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln133_fu_658_p0,
        din1 => mul_ln133_fu_658_p1,
        dout => mul_ln133_fu_658_p2);

    sparsemux_11_3_32_1_1_U159 : component bnn_top_sparsemux_11_3_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "010",
        din0_WIDTH => 32,
        CASE1 => "011",
        din1_WIDTH => 32,
        CASE2 => "100",
        din2_WIDTH => 32,
        CASE3 => "000",
        din3_WIDTH => 32,
        CASE4 => "001",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0,
        def => s2_fu_708_p11,
        sel => trunc_ln130_2_reg_895_pp0_iter10_reg,
        dout => s2_fu_708_p13);

    sparsemux_11_3_32_1_1_x_U160 : component bnn_top_sparsemux_11_3_32_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "001",
        din0_WIDTH => 32,
        CASE1 => "010",
        din1_WIDTH => 32,
        CASE2 => "011",
        din2_WIDTH => 32,
        CASE3 => "100",
        din3_WIDTH => 32,
        CASE4 => "000",
        din4_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0,
        din1 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0,
        din2 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0,
        din3 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0,
        din4 => bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0,
        def => s3_fu_735_p11,
        sel => trunc_ln130_2_reg_895_pp0_iter10_reg,
        dout => s3_fu_735_p13);

    am_addmul_5ns_5ns_7ns_13_4_1_U161 : component bnn_top_am_addmul_5ns_5ns_7ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        din2_WIDTH => 7,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_821_p0,
        din1 => grp_fu_821_p1,
        din2 => grp_fu_821_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_821_p3);

    flow_control_loop_pipe_sequential_init_U : component bnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten66_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln127_fu_354_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten66_fu_98 <= add_ln127_fu_360_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten66_fu_98 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    ph_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln127_fu_354_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    ph_fu_94 <= select_ln127_1_fu_392_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ph_fu_94 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    pw_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln127_fu_354_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    pw_fu_90 <= add_ln128_fu_470_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    pw_fu_90 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                m_9_reg_1003 <= m_9_fu_689_p3;
                select_ln127_reg_865_pp0_iter10_reg <= select_ln127_reg_865_pp0_iter9_reg;
                select_ln127_reg_865_pp0_iter2_reg <= select_ln127_reg_865_pp0_iter1_reg;
                select_ln127_reg_865_pp0_iter3_reg <= select_ln127_reg_865_pp0_iter2_reg;
                select_ln127_reg_865_pp0_iter4_reg <= select_ln127_reg_865_pp0_iter3_reg;
                select_ln127_reg_865_pp0_iter5_reg <= select_ln127_reg_865_pp0_iter4_reg;
                select_ln127_reg_865_pp0_iter6_reg <= select_ln127_reg_865_pp0_iter5_reg;
                select_ln127_reg_865_pp0_iter7_reg <= select_ln127_reg_865_pp0_iter6_reg;
                select_ln127_reg_865_pp0_iter8_reg <= select_ln127_reg_865_pp0_iter7_reg;
                select_ln127_reg_865_pp0_iter9_reg <= select_ln127_reg_865_pp0_iter8_reg;
                tmp_51_reg_890 <= tmp_51_fu_491_p1(12 downto 9);
                tmp_51_reg_890_pp0_iter4_reg <= tmp_51_reg_890;
                tmp_51_reg_890_pp0_iter5_reg <= tmp_51_reg_890_pp0_iter4_reg;
                tmp_51_reg_890_pp0_iter6_reg <= tmp_51_reg_890_pp0_iter5_reg;
                tmp_51_reg_890_pp0_iter7_reg <= tmp_51_reg_890_pp0_iter6_reg;
                tmp_51_reg_890_pp0_iter8_reg <= tmp_51_reg_890_pp0_iter7_reg;
                trunc_ln130_1_reg_878_pp0_iter2_reg <= trunc_ln130_1_reg_878_pp0_iter1_reg;
                trunc_ln130_1_reg_878_pp0_iter3_reg <= trunc_ln130_1_reg_878_pp0_iter2_reg;
                trunc_ln130_1_reg_878_pp0_iter4_reg <= trunc_ln130_1_reg_878_pp0_iter3_reg;
                trunc_ln130_1_reg_878_pp0_iter5_reg <= trunc_ln130_1_reg_878_pp0_iter4_reg;
                trunc_ln130_1_reg_878_pp0_iter6_reg <= trunc_ln130_1_reg_878_pp0_iter5_reg;
                trunc_ln130_1_reg_878_pp0_iter7_reg <= trunc_ln130_1_reg_878_pp0_iter6_reg;
                trunc_ln130_1_reg_878_pp0_iter8_reg <= trunc_ln130_1_reg_878_pp0_iter7_reg;
                trunc_ln130_1_reg_878_pp0_iter9_reg <= trunc_ln130_1_reg_878_pp0_iter8_reg;
                trunc_ln130_2_reg_895 <= trunc_ln130_2_fu_500_p1;
                trunc_ln130_2_reg_895_pp0_iter10_reg <= trunc_ln130_2_reg_895_pp0_iter9_reg;
                trunc_ln130_2_reg_895_pp0_iter9_reg <= trunc_ln130_2_reg_895;
                trunc_ln130_reg_870_pp0_iter10_reg <= trunc_ln130_reg_870_pp0_iter9_reg;
                trunc_ln130_reg_870_pp0_iter2_reg <= trunc_ln130_reg_870_pp0_iter1_reg;
                trunc_ln130_reg_870_pp0_iter3_reg <= trunc_ln130_reg_870_pp0_iter2_reg;
                trunc_ln130_reg_870_pp0_iter4_reg <= trunc_ln130_reg_870_pp0_iter3_reg;
                trunc_ln130_reg_870_pp0_iter5_reg <= trunc_ln130_reg_870_pp0_iter4_reg;
                trunc_ln130_reg_870_pp0_iter6_reg <= trunc_ln130_reg_870_pp0_iter5_reg;
                trunc_ln130_reg_870_pp0_iter7_reg <= trunc_ln130_reg_870_pp0_iter6_reg;
                trunc_ln130_reg_870_pp0_iter8_reg <= trunc_ln130_reg_870_pp0_iter7_reg;
                trunc_ln130_reg_870_pp0_iter9_reg <= trunc_ln130_reg_870_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln127_reg_865 <= select_ln127_fu_378_p3;
                select_ln127_reg_865_pp0_iter1_reg <= select_ln127_reg_865;
                sext_ln135_cast_reg_856 <= sext_ln135_cast_fu_332_p1;
                trunc_ln130_1_reg_878 <= trunc_ln130_1_fu_430_p1;
                trunc_ln130_1_reg_878_pp0_iter1_reg <= trunc_ln130_1_reg_878;
                trunc_ln130_reg_870 <= trunc_ln130_fu_400_p1;
                trunc_ln130_reg_870_pp0_iter1_reg <= trunc_ln130_reg_870;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln127_1_fu_386_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ph_load) + unsigned(ap_const_lv3_1));
    add_ln127_fu_360_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten66_load) + unsigned(ap_const_lv5_1));
    add_ln128_fu_470_p2 <= std_logic_vector(unsigned(select_ln127_fu_378_p3) + unsigned(ap_const_lv3_1));
    add_ln130_2_fu_454_p2 <= std_logic_vector(unsigned(p_shl_fu_404_p3) + unsigned(zext_ln130_fu_420_p1));
    add_ln130_fu_444_p2 <= std_logic_vector(unsigned(zext_ln130_1_fu_440_p1) + unsigned(sub_ln130_fu_424_p2));
    add_ln135_fu_810_p2 <= std_logic_vector(unsigned(tmp12_fu_802_p4) + unsigned(zext_ln128_fu_704_p1));
    add_ln7_fu_512_p5 <= (((trunc_ln130_reg_870_pp0_iter8_reg & ap_const_lv1_0) & trunc_ln130_1_reg_878_pp0_iter8_reg) & ap_const_lv1_1);
    add_ln8_fu_605_p5 <= (((trunc_ln130_reg_870_pp0_iter9_reg & ap_const_lv1_1) & trunc_ln130_1_reg_878_pp0_iter9_reg) & ap_const_lv1_0);
    add_ln9_fu_644_p5 <= (((trunc_ln130_reg_870_pp0_iter9_reg & ap_const_lv1_1) & trunc_ln130_1_reg_878_pp0_iter9_reg) & ap_const_lv1_1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln127_fu_354_p2)
    begin
        if (((icmp_ln127_fu_354_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten66_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten66_fu_98)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten66_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten66_load <= indvar_flatten66_fu_98;
        end if; 
    end process;


    ap_sig_allocacmp_ph_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ph_fu_94)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ph_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_ph_load <= ph_fu_94;
        end if; 
    end process;


    ap_sig_allocacmp_pw_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, pw_fu_90, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_pw_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_pw_load <= pw_fu_90;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln130_2_reg_895_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln132_fu_635_p1, zext_ln133_fu_674_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= zext_ln133_fu_674_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= zext_ln132_fu_635_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln130_2_reg_895, zext_ln130_5_fu_504_p1, ap_block_pp0_stage0, zext_ln131_fu_542_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895 = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= zext_ln131_fu_542_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895 = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= zext_ln130_5_fu_504_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_4)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_2)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln130_2_reg_895_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln132_fu_635_p1, zext_ln133_fu_674_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= zext_ln133_fu_674_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= zext_ln132_fu_635_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln130_2_reg_895, zext_ln130_5_fu_504_p1, ap_block_pp0_stage0, zext_ln131_fu_542_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895 = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= zext_ln131_fu_542_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895 = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= zext_ln130_5_fu_504_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_3)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_1)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln130_2_reg_895_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln132_fu_635_p1, zext_ln133_fu_674_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= zext_ln133_fu_674_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= zext_ln132_fu_635_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln130_2_reg_895, zext_ln130_5_fu_504_p1, ap_block_pp0_stage0, zext_ln131_fu_542_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895 = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= zext_ln131_fu_542_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895 = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= zext_ln130_5_fu_504_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_2)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_0)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln130_2_reg_895_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln132_fu_635_p1, zext_ln133_fu_674_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= zext_ln133_fu_674_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_2)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= zext_ln132_fu_635_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln130_2_reg_895, zext_ln130_5_fu_504_p1, ap_block_pp0_stage0, zext_ln131_fu_542_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895 = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= zext_ln131_fu_542_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895 = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= zext_ln130_5_fu_504_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_2)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_0)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local_assign_proc : process(ap_enable_reg_pp0_iter10, trunc_ln130_2_reg_895_pp0_iter9_reg, ap_block_pp0_stage0, zext_ln132_fu_635_p1, zext_ln133_fu_674_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_0)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= zext_ln133_fu_674_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_1)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= zext_ln132_fu_635_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local_assign_proc : process(ap_enable_reg_pp0_iter9, trunc_ln130_2_reg_895, zext_ln130_5_fu_504_p1, ap_block_pp0_stage0, zext_ln131_fu_542_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
            if ((trunc_ln130_2_reg_895 = ap_const_lv3_3)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= zext_ln131_fu_542_p1(8 - 1 downto 0);
            elsif ((trunc_ln130_2_reg_895 = ap_const_lv3_4)) then 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= zext_ln130_5_fu_504_p1(8 - 1 downto 0);
            else 
                bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= "XXXXXXXX";
            end if;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895_pp0_iter9_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (trunc_ln130_2_reg_895_pp0_iter9_reg = ap_const_lv3_0)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1 <= bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local;

    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, trunc_ln130_2_reg_895)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_4)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (trunc_ln130_2_reg_895 = ap_const_lv3_3)))) then 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local <= ap_const_logic_1;
        else 
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_464_p1 <= ap_const_lv5_5(4 - 1 downto 0);
    grp_fu_821_p0 <= grp_fu_821_p00(5 - 1 downto 0);
    grp_fu_821_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln130_fu_444_p2),6));
    grp_fu_821_p1 <= grp_fu_821_p10(5 - 1 downto 0);
    grp_fu_821_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln130_2_fu_454_p2),6));
    grp_fu_821_p2 <= ap_const_lv13_67(7 - 1 downto 0);
    icmp_ln127_fu_354_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten66_load = ap_const_lv5_10) else "0";
    icmp_ln128_fu_372_p2 <= "1" when (ap_sig_allocacmp_pw_load = ap_const_lv3_4) else "0";
    icmp_ln134_1_fu_762_p2 <= "1" when (signed(s2_fu_708_p13) > signed(m_9_reg_1003)) else "0";
    icmp_ln134_2_fu_774_p2 <= "1" when (signed(s3_fu_735_p13) > signed(m_11_fu_767_p3)) else "0";
    icmp_ln134_fu_683_p2 <= "1" when (signed(s1_fu_578_p13) > signed(s0_fu_551_p13)) else "0";
    icmp_ln135_fu_796_p2 <= "1" when (signed(shl_ln_fu_788_p3) > signed(sext_ln135_cast_reg_856)) else "0";
    l3_address0 <= zext_ln135_fu_816_p1(10 - 1 downto 0);
    l3_ce0 <= l3_ce0_local;

    l3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            l3_ce0_local <= ap_const_logic_1;
        else 
            l3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l3_d0 <= icmp_ln135_fu_796_p2;
    l3_we0 <= l3_we0_local;

    l3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            l3_we0_local <= ap_const_logic_1;
        else 
            l3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_11_fu_767_p3 <= 
        s2_fu_708_p13 when (icmp_ln134_1_fu_762_p2(0) = '1') else 
        m_9_reg_1003;
    m_9_fu_689_p3 <= 
        s1_fu_578_p13 when (icmp_ln134_fu_683_p2(0) = '1') else 
        s0_fu_551_p13;
    mul_ln131_fu_526_p0 <= mul_ln131_fu_526_p00(6 - 1 downto 0);
    mul_ln131_fu_526_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln7_fu_512_p5),13));
    mul_ln131_fu_526_p1 <= ap_const_lv13_67(8 - 1 downto 0);
    mul_ln132_fu_619_p0 <= mul_ln132_fu_619_p00(6 - 1 downto 0);
    mul_ln132_fu_619_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln8_fu_605_p5),13));
    mul_ln132_fu_619_p1 <= ap_const_lv13_67(8 - 1 downto 0);
    mul_ln133_fu_658_p0 <= mul_ln133_fu_658_p00(6 - 1 downto 0);
    mul_ln133_fu_658_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln9_fu_644_p5),13));
    mul_ln133_fu_658_p1 <= ap_const_lv13_67(8 - 1 downto 0);
    p_shl_fu_404_p3 <= (trunc_ln130_fu_400_p1 & ap_const_lv3_0);
    s0_fu_551_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    s1_fu_578_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    s2_fu_708_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    s3_fu_735_p11 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    select_ln127_1_fu_392_p3 <= 
        add_ln127_1_fu_386_p2 when (icmp_ln128_fu_372_p2(0) = '1') else 
        ap_sig_allocacmp_ph_load;
    select_ln127_fu_378_p3 <= 
        ap_const_lv3_0 when (icmp_ln128_fu_372_p2(0) = '1') else 
        ap_sig_allocacmp_pw_load;
    select_ln134_fu_780_p3 <= 
        s3_fu_735_p13 when (icmp_ln134_2_fu_774_p2(0) = '1') else 
        m_11_fu_767_p3;
        sext_ln135_cast_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln135),40));

    shl_ln130_fu_434_p2 <= std_logic_vector(shift_left(unsigned(select_ln127_fu_378_p3),to_integer(unsigned('0' & ap_const_lv3_1(3-1 downto 0)))));
    shl_ln135_1_fu_697_p3 <= (trunc_ln130_reg_870_pp0_iter10_reg & ap_const_lv2_0);
    shl_ln_fu_788_p3 <= (select_ln134_fu_780_p3 & ap_const_lv8_0);
    sub_ln130_fu_424_p2 <= std_logic_vector(unsigned(p_shl_fu_404_p3) - unsigned(zext_ln130_fu_420_p1));
    tmp12_fu_802_p4 <= ((oc_2 & ap_const_lv1_0) & select_ln127_reg_865_pp0_iter10_reg);
    tmp_51_fu_491_p1 <= grp_fu_821_p3;
    tmp_52_fu_532_p4 <= mul_ln131_fu_526_p2(12 downto 9);
    tmp_53_fu_625_p4 <= mul_ln132_fu_619_p2(12 downto 9);
    tmp_54_fu_664_p4 <= mul_ln133_fu_658_p2(12 downto 9);
    tmp_fu_412_p3 <= (select_ln127_1_fu_392_p3 & ap_const_lv1_0);
    trunc_ln130_1_fu_430_p1 <= select_ln127_fu_378_p3(2 - 1 downto 0);
    trunc_ln130_2_fu_500_p1 <= grp_fu_464_p2(3 - 1 downto 0);
    trunc_ln130_fu_400_p1 <= select_ln127_1_fu_392_p3(2 - 1 downto 0);
    zext_ln128_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln135_1_fu_697_p3),10));
    zext_ln130_1_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln130_fu_434_p2),5));
    zext_ln130_5_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_51_reg_890_pp0_iter8_reg),64));
    zext_ln130_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_412_p3),5));
    zext_ln131_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_52_fu_532_p4),64));
    zext_ln132_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_53_fu_625_p4),64));
    zext_ln133_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_54_fu_664_p4),64));
    zext_ln135_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln135_fu_810_p2),64));
end behav;
