// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module bnn_top_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_0_address0,
        img_0_ce0,
        img_0_q0,
        img_0_address1,
        img_0_ce1,
        img_0_q1,
        img_1_address0,
        img_1_ce0,
        img_1_q0,
        img_1_address1,
        img_1_ce1,
        img_1_q1,
        img_2_address0,
        img_2_ce0,
        img_2_q0,
        img_2_address1,
        img_2_ce1,
        img_2_q1,
        img_3_address0,
        img_3_ce0,
        img_3_q0,
        img_3_address1,
        img_3_ce1,
        img_3_q1,
        W1_load_1,
        empty_34,
        W1_load_2,
        empty_35,
        W1_load_3,
        empty_36,
        W1_load_4,
        empty_37,
        cmp38_1_1,
        W1_load_5,
        empty_38,
        W1_load_6,
        empty_39,
        W1_load_7,
        empty_40,
        W1_load_8,
        empty,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] img_0_address0;
output   img_0_ce0;
input  [31:0] img_0_q0;
output  [7:0] img_0_address1;
output   img_0_ce1;
input  [31:0] img_0_q1;
output  [7:0] img_1_address0;
output   img_1_ce0;
input  [31:0] img_1_q0;
output  [7:0] img_1_address1;
output   img_1_ce1;
input  [31:0] img_1_q1;
output  [7:0] img_2_address0;
output   img_2_ce0;
input  [31:0] img_2_q0;
output  [7:0] img_2_address1;
output   img_2_ce1;
input  [31:0] img_2_q1;
output  [7:0] img_3_address0;
output   img_3_ce0;
input  [31:0] img_3_q0;
output  [7:0] img_3_address1;
output   img_3_ce1;
input  [31:0] img_3_q1;
input  [31:0] W1_load_1;
input  [4:0] empty_34;
input  [31:0] W1_load_2;
input  [4:0] empty_35;
input  [31:0] W1_load_3;
input  [4:0] empty_36;
input  [31:0] W1_load_4;
input  [4:0] empty_37;
input  [0:0] cmp38_1_1;
input  [31:0] W1_load_5;
input  [4:0] empty_38;
input  [31:0] W1_load_6;
input  [4:0] empty_39;
input  [31:0] W1_load_7;
input  [4:0] empty_40;
input  [31:0] W1_load_8;
input  [4:0] empty;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_we0;
output  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_d0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_we0;
output  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_d0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_we0;
output  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_d0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_we0;
output  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_d0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_we0;
output  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln50_reg_1639;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [31:0] grp_fu_711_p11;
reg   [31:0] reg_734;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln50_fu_756_p2;
reg   [0:0] icmp_ln50_reg_1639_pp0_iter1_reg;
reg   [0:0] icmp_ln50_reg_1639_pp0_iter2_reg;
reg   [0:0] icmp_ln50_reg_1639_pp0_iter3_reg;
wire   [5:0] select_ln50_fu_780_p3;
reg   [5:0] select_ln50_reg_1643;
reg   [5:0] select_ln50_reg_1643_pp0_iter1_reg;
reg   [5:0] select_ln50_reg_1643_pp0_iter2_reg;
wire   [5:0] select_ln50_1_fu_800_p3;
reg   [5:0] select_ln50_1_reg_1649;
reg   [5:0] select_ln50_1_reg_1649_pp0_iter1_reg;
reg   [5:0] select_ln50_1_reg_1649_pp0_iter2_reg;
reg   [5:0] select_ln50_1_reg_1649_pp0_iter3_reg;
reg   [5:0] select_ln50_1_reg_1649_pp0_iter4_reg;
wire   [5:0] select_ln50_2_fu_808_p3;
reg   [5:0] select_ln50_2_reg_1656;
reg   [5:0] select_ln50_2_reg_1656_pp0_iter1_reg;
reg   [5:0] select_ln50_2_reg_1656_pp0_iter2_reg;
wire   [4:0] trunc_ln63_fu_816_p1;
reg   [4:0] trunc_ln63_reg_1662;
reg   [4:0] trunc_ln63_reg_1662_pp0_iter1_reg;
reg   [4:0] trunc_ln63_reg_1662_pp0_iter2_reg;
reg   [4:0] trunc_ln63_reg_1662_pp0_iter3_reg;
wire   [1:0] trunc_ln51_fu_834_p1;
reg   [1:0] trunc_ln51_reg_1669;
reg   [1:0] trunc_ln51_reg_1669_pp0_iter1_reg;
reg   [1:0] trunc_ln51_reg_1669_pp0_iter2_reg;
reg   [1:0] trunc_ln51_reg_1669_pp0_iter3_reg;
reg   [1:0] trunc_ln51_reg_1669_pp0_iter4_reg;
wire   [0:0] cmp_fu_838_p3;
reg   [0:0] cmp_reg_1679;
reg   [0:0] cmp_reg_1679_pp0_iter1_reg;
reg   [0:0] cmp_reg_1679_pp0_iter2_reg;
reg   [0:0] cmp_reg_1679_pp0_iter3_reg;
reg   [2:0] lshr_ln58_1_reg_1684;
reg   [2:0] lshr_ln58_1_reg_1684_pp0_iter1_reg;
reg   [2:0] lshr_ln58_1_reg_1684_pp0_iter2_reg;
reg   [2:0] lshr_ln58_1_reg_1684_pp0_iter3_reg;
wire   [0:0] cmp38_s_fu_856_p3;
reg   [0:0] cmp38_s_reg_1691;
reg   [0:0] cmp38_s_reg_1691_pp0_iter1_reg;
reg   [0:0] cmp38_s_reg_1691_pp0_iter2_reg;
reg   [0:0] cmp38_s_reg_1691_pp0_iter3_reg;
wire   [0:0] cmp38_3_fu_864_p3;
reg   [0:0] cmp38_3_reg_1696;
reg   [0:0] cmp38_3_reg_1696_pp0_iter1_reg;
reg   [0:0] cmp38_3_reg_1696_pp0_iter2_reg;
reg   [0:0] cmp38_3_reg_1696_pp0_iter3_reg;
wire   [0:0] cmp38_1_fu_872_p3;
reg   [0:0] cmp38_1_reg_1701;
reg   [0:0] cmp38_1_reg_1701_pp0_iter1_reg;
reg   [0:0] cmp38_1_reg_1701_pp0_iter2_reg;
reg   [0:0] cmp38_1_reg_1701_pp0_iter3_reg;
wire   [6:0] add_ln58_5_fu_880_p2;
reg   [6:0] add_ln58_5_reg_1706;
reg   [6:0] add_ln58_5_reg_1706_pp0_iter1_reg;
reg   [6:0] add_ln58_5_reg_1706_pp0_iter2_reg;
wire   [0:0] cmp38_1_2_fu_892_p3;
reg   [0:0] cmp38_1_2_reg_1712;
reg   [0:0] cmp38_1_2_reg_1712_pp0_iter1_reg;
reg   [0:0] cmp38_1_2_reg_1712_pp0_iter2_reg;
reg   [0:0] cmp38_1_2_reg_1712_pp0_iter3_reg;
reg   [0:0] cmp38_1_2_reg_1712_pp0_iter4_reg;
wire   [0:0] cmp38_2_fu_900_p3;
reg   [0:0] cmp38_2_reg_1717;
reg   [0:0] cmp38_2_reg_1717_pp0_iter1_reg;
reg   [0:0] cmp38_2_reg_1717_pp0_iter2_reg;
reg   [0:0] cmp38_2_reg_1717_pp0_iter3_reg;
reg   [0:0] cmp38_2_reg_1717_pp0_iter4_reg;
wire   [0:0] cmp38_2_1_fu_908_p3;
reg   [0:0] cmp38_2_1_reg_1722;
reg   [0:0] cmp38_2_1_reg_1722_pp0_iter1_reg;
reg   [0:0] cmp38_2_1_reg_1722_pp0_iter2_reg;
reg   [0:0] cmp38_2_1_reg_1722_pp0_iter3_reg;
reg   [0:0] cmp38_2_1_reg_1722_pp0_iter4_reg;
wire   [0:0] cmp38_2_2_fu_916_p3;
reg   [0:0] cmp38_2_2_reg_1727;
reg   [0:0] cmp38_2_2_reg_1727_pp0_iter1_reg;
reg   [0:0] cmp38_2_2_reg_1727_pp0_iter2_reg;
reg   [0:0] cmp38_2_2_reg_1727_pp0_iter3_reg;
reg   [0:0] cmp38_2_2_reg_1727_pp0_iter4_reg;
wire   [5:0] add_ln56_3_fu_934_p2;
reg   [5:0] add_ln56_3_reg_1732;
reg   [5:0] add_ln56_3_reg_1732_pp0_iter1_reg;
reg   [5:0] add_ln56_3_reg_1732_pp0_iter2_reg;
reg   [5:0] add_ln56_3_reg_1732_pp0_iter3_reg;
reg   [5:0] add_ln56_3_reg_1732_pp0_iter4_reg;
reg   [3:0] lshr_ln58_2_reg_1739;
reg   [3:0] lshr_ln58_2_reg_1739_pp0_iter1_reg;
reg   [3:0] lshr_ln58_2_reg_1739_pp0_iter2_reg;
wire   [5:0] add_ln56_fu_954_p2;
reg   [5:0] add_ln56_reg_1744;
wire   [0:0] tmp_39_fu_959_p3;
reg   [0:0] tmp_39_reg_1749;
wire   [4:0] trunc_ln58_fu_967_p1;
reg   [4:0] trunc_ln58_reg_1754;
wire   [5:0] add_ln56_2_fu_971_p2;
reg   [5:0] add_ln56_2_reg_1760;
reg   [3:0] trunc_ln1_reg_1766;
wire   [0:0] icmp_ln57_fu_1007_p2;
reg   [0:0] icmp_ln57_reg_1771;
reg   [0:0] tmp_44_reg_1776;
reg   [7:0] tmp_46_reg_1782;
reg   [7:0] tmp_46_reg_1782_pp0_iter4_reg;
wire   [0:0] icmp_ln57_1_fu_1203_p2;
reg   [0:0] icmp_ln57_1_reg_1907;
wire   [7:0] add_ln58_9_fu_1209_p2;
reg   [7:0] add_ln58_9_reg_1912;
reg   [4:0] tmp_s_reg_1917;
wire   [7:0] add_ln58_10_fu_1225_p2;
reg   [7:0] add_ln58_10_reg_1922;
wire   [31:0] acc_16_fu_1404_p3;
reg   [31:0] acc_16_reg_1927;
wire   [31:0] grp_fu_688_p11;
reg   [31:0] v_4_reg_1933;
wire   [31:0] acc_34_fu_1540_p3;
reg   [31:0] acc_34_reg_1999;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln58_fu_1103_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln58_1_fu_1117_p1;
wire   [63:0] zext_ln58_3_fu_1134_p1;
wire   [63:0] zext_ln58_4_fu_1148_p1;
wire   [63:0] zext_ln58_8_fu_1162_p1;
wire   [63:0] zext_ln58_9_fu_1176_p1;
wire   [63:0] zext_ln58_10_fu_1411_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln58_11_fu_1424_p1;
wire   [63:0] zext_ln58_12_fu_1432_p1;
wire   [63:0] zext_ln58_7_fu_1548_p1;
reg   [5:0] iw_fu_162;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_iw_load;
reg   [5:0] oh_fu_166;
reg   [5:0] ap_sig_allocacmp_oh_load;
reg   [10:0] indvar_flatten_fu_170;
wire   [10:0] add_ln50_fu_762_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
reg    img_0_ce1_local;
reg   [7:0] img_0_address1_local;
reg    img_0_ce0_local;
reg   [7:0] img_0_address0_local;
reg    img_1_ce1_local;
reg   [7:0] img_1_address1_local;
reg    img_1_ce0_local;
reg   [7:0] img_1_address0_local;
reg    img_2_ce1_local;
reg   [7:0] img_2_address1_local;
reg    img_2_ce0_local;
reg   [7:0] img_2_address0_local;
reg    img_3_ce1_local;
reg   [7:0] img_3_address1_local;
reg    img_3_ce0_local;
reg   [7:0] img_3_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_we0_local;
wire   [2:0] trunc_ln58_1_fu_1556_p1;
wire   [31:0] acc_40_fu_1589_p3;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;
wire   [31:0] grp_fu_665_p9;
reg   [1:0] grp_fu_665_p10;
wire   [31:0] grp_fu_688_p9;
reg   [1:0] grp_fu_688_p10;
wire   [31:0] grp_fu_711_p9;
reg   [1:0] grp_fu_711_p10;
wire   [0:0] icmp_ln51_fu_774_p2;
wire   [5:0] add_ln56_1_fu_788_p2;
wire   [5:0] add_ln56_4_fu_794_p2;
wire   [5:0] shl_ln63_fu_820_p2;
wire   [6:0] zext_ln51_fu_830_p1;
wire   [6:0] zext_ln56_fu_826_p1;
wire   [6:0] grp_fu_886_p0;
wire   [3:0] grp_fu_886_p1;
wire   [5:0] or_ln57_1_fu_986_p2;
wire   [0:0] tmp_42_fu_991_p3;
wire   [1:0] tmp_43_fu_999_p3;
wire   [6:0] tmp_45_fu_1031_p3;
wire   [9:0] p_shl_fu_1024_p3;
wire   [9:0] zext_ln58_6_fu_1038_p1;
wire   [9:0] zext_ln58_5_fu_1021_p1;
wire   [9:0] sub_ln58_fu_1042_p2;
wire   [9:0] add_ln58_6_fu_1048_p2;
wire   [9:0] mul_ln58_fu_1058_p0;
wire   [11:0] mul_ln58_fu_1058_p1;
wire   [20:0] mul_ln58_fu_1058_p2;
wire   [7:0] shl_ln58_1_fu_1081_p3;
wire  signed [7:0] sext_ln58_fu_1094_p1;
wire   [7:0] shl_ln1_fu_1074_p3;
wire   [7:0] add_ln58_1_fu_1097_p2;
wire   [7:0] add_ln58_2_fu_1111_p3;
wire   [7:0] zext_ln58_2_fu_1125_p1;
wire   [7:0] add_ln58_3_fu_1128_p2;
wire   [7:0] add_ln58_4_fu_1142_p2;
wire   [7:0] add_ln58_7_fu_1156_p3;
wire   [7:0] add_ln58_8_fu_1170_p2;
wire   [5:0] or_ln57_2_fu_1184_p2;
wire   [0:0] tmp_48_fu_1188_p3;
wire   [1:0] tmp_49_fu_1196_p3;
wire   [7:0] add_ln58_fu_1088_p2;
wire   [5:0] or_ln57_fu_1231_p2;
wire   [31:0] v_fu_1243_p9;
wire   [31:0] v_fu_1243_p11;
wire   [31:0] acc_fu_1266_p2;
wire   [0:0] tmp_41_fu_1235_p3;
wire   [31:0] acc_22_fu_1272_p3;
wire   [31:0] v_1_fu_1287_p9;
wire   [31:0] v_1_fu_1287_p11;
wire   [31:0] acc_2_fu_1279_p3;
wire   [31:0] acc_27_fu_1310_p2;
wire   [31:0] acc_29_fu_1316_p2;
wire   [31:0] acc_35_fu_1322_p3;
wire   [31:0] v_2_fu_1336_p9;
wire   [31:0] v_2_fu_1336_p11;
wire   [31:0] acc_6_fu_1329_p3;
wire   [31:0] acc_37_fu_1359_p2;
wire   [31:0] acc_41_fu_1365_p2;
wire   [31:0] acc_42_fu_1371_p3;
wire   [31:0] grp_fu_665_p11;
wire   [31:0] acc_10_fu_1378_p3;
wire   [31:0] acc_43_fu_1385_p2;
wire   [31:0] acc_44_fu_1391_p2;
wire   [31:0] acc_45_fu_1397_p3;
wire   [7:0] add_ln58_s_fu_1418_p3;
wire   [31:0] acc_46_fu_1446_p2;
wire   [31:0] acc_47_fu_1450_p2;
wire   [31:0] acc_48_fu_1454_p3;
wire   [31:0] acc_49_fu_1468_p2;
wire   [31:0] acc_50_fu_1474_p2;
wire   [0:0] tmp_47_fu_1461_p3;
wire   [31:0] acc_51_fu_1480_p3;
wire   [31:0] acc_24_fu_1487_p3;
wire   [31:0] acc_52_fu_1495_p2;
wire   [31:0] acc_53_fu_1501_p2;
wire   [31:0] acc_54_fu_1507_p3;
wire   [31:0] acc_30_fu_1514_p3;
wire   [31:0] acc_55_fu_1521_p2;
wire   [31:0] acc_56_fu_1527_p2;
wire   [0:0] tmp_40_fu_1439_p3;
wire   [31:0] acc_57_fu_1533_p3;
wire   [2:0] grp_fu_886_p2;
wire   [5:0] or_ln57_3_fu_1560_p2;
wire   [31:0] acc_58_fu_1572_p2;
wire   [31:0] acc_59_fu_1577_p2;
wire   [0:0] tmp_50_fu_1564_p3;
wire   [31:0] acc_60_fu_1582_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage0;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [20:0] mul_ln58_fu_1058_p00;
reg    ap_condition_402;
wire   [1:0] grp_fu_665_p1;
wire  signed [1:0] grp_fu_665_p3;
wire  signed [1:0] grp_fu_665_p5;
wire   [1:0] grp_fu_665_p7;
wire   [1:0] grp_fu_688_p1;
wire   [1:0] grp_fu_688_p3;
wire  signed [1:0] grp_fu_688_p5;
wire  signed [1:0] grp_fu_688_p7;
wire  signed [1:0] grp_fu_711_p1;
wire   [1:0] grp_fu_711_p3;
wire   [1:0] grp_fu_711_p5;
wire  signed [1:0] grp_fu_711_p7;
wire   [0:0] cmp_fu_838_p0;
wire   [0:0] cmp38_s_fu_856_p0;
wire   [0:0] cmp38_3_fu_864_p0;
wire   [0:0] cmp38_1_fu_872_p0;
wire   [0:0] cmp38_1_2_fu_892_p0;
wire   [0:0] cmp38_2_fu_900_p0;
wire   [0:0] cmp38_2_1_fu_908_p0;
wire   [0:0] cmp38_2_2_fu_916_p0;
wire   [1:0] v_fu_1243_p1;
wire  signed [1:0] v_fu_1243_p3;
wire  signed [1:0] v_fu_1243_p5;
wire   [1:0] v_fu_1243_p7;
wire   [1:0] v_1_fu_1287_p1;
wire   [1:0] v_1_fu_1287_p3;
wire  signed [1:0] v_1_fu_1287_p5;
wire  signed [1:0] v_1_fu_1287_p7;
wire  signed [1:0] v_2_fu_1336_p1;
wire   [1:0] v_2_fu_1336_p3;
wire   [1:0] v_2_fu_1336_p5;
wire  signed [1:0] v_2_fu_1336_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 iw_fu_162 = 6'd0;
#0 oh_fu_166 = 6'd0;
#0 indvar_flatten_fu_170 = 11'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U1(
    .din0(img_0_q0),
    .din1(img_1_q0),
    .din2(img_2_q0),
    .din3(img_3_q0),
    .def(grp_fu_665_p9),
    .sel(grp_fu_665_p10),
    .dout(grp_fu_665_p11)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U2(
    .din0(img_0_q0),
    .din1(img_1_q0),
    .din2(img_2_q0),
    .din3(img_3_q0),
    .def(grp_fu_688_p9),
    .sel(grp_fu_688_p10),
    .dout(grp_fu_688_p11)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h3 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h2 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U3(
    .din0(img_0_q0),
    .din1(img_1_q0),
    .din2(img_2_q0),
    .din3(img_3_q0),
    .def(grp_fu_711_p9),
    .sel(grp_fu_711_p10),
    .dout(grp_fu_711_p11)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U4(
    .din(W1_load_1),
    .sel(empty_34),
    .dout(cmp_fu_838_p3)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U5(
    .din(W1_load_2),
    .sel(empty_35),
    .dout(cmp38_s_fu_856_p3)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U6(
    .din(W1_load_3),
    .sel(empty_36),
    .dout(cmp38_3_fu_864_p3)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U7(
    .din(W1_load_4),
    .sel(empty_37),
    .dout(cmp38_1_fu_872_p3)
);

bnn_top_urem_7ns_4ns_3_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 11 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_7ns_4ns_3_11_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_886_p0),
    .din1(grp_fu_886_p1),
    .ce(1'b1),
    .dout(grp_fu_886_p2)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U9(
    .din(W1_load_5),
    .sel(empty_38),
    .dout(cmp38_1_2_fu_892_p3)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U10(
    .din(W1_load_6),
    .sel(empty_39),
    .dout(cmp38_2_fu_900_p3)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U11(
    .din(W1_load_7),
    .sel(empty_40),
    .dout(cmp38_2_1_fu_908_p3)
);

bnn_top_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U12(
    .din(W1_load_8),
    .sel(empty),
    .dout(cmp38_2_2_fu_916_p3)
);

bnn_top_mul_10ns_12ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
mul_10ns_12ns_21_1_1_U13(
    .din0(mul_ln58_fu_1058_p0),
    .din1(mul_ln58_fu_1058_p1),
    .dout(mul_ln58_fu_1058_p2)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h3 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U14(
    .din0(img_0_q1),
    .din1(img_1_q1),
    .din2(img_2_q1),
    .din3(img_3_q1),
    .def(v_fu_1243_p9),
    .sel(trunc_ln51_reg_1669_pp0_iter3_reg),
    .dout(v_fu_1243_p11)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U15(
    .din0(img_0_q1),
    .din1(img_1_q1),
    .din2(img_2_q1),
    .din3(img_3_q1),
    .def(v_1_fu_1287_p9),
    .sel(trunc_ln51_reg_1669_pp0_iter3_reg),
    .dout(v_1_fu_1287_p11)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h3 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h2 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U16(
    .din0(img_0_q1),
    .din1(img_1_q1),
    .din2(img_2_q1),
    .din3(img_3_q1),
    .def(v_2_fu_1336_p9),
    .sel(trunc_ln51_reg_1669_pp0_iter3_reg),
    .dout(v_2_fu_1336_p11)
);

bnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter4_stage0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln50_fu_756_p2 == 1'd0))) begin
            indvar_flatten_fu_170 <= add_ln50_fu_762_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_170 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        iw_fu_162 <= 6'd0;
    end else if (((icmp_ln50_reg_1639 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        iw_fu_162 <= add_ln56_3_fu_934_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln50_fu_756_p2 == 1'd0))) begin
            oh_fu_166 <= select_ln50_2_fu_808_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oh_fu_166 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_16_reg_1927 <= acc_16_fu_1404_p3;
        add_ln56_2_reg_1760 <= add_ln56_2_fu_971_p2;
        add_ln56_reg_1744 <= add_ln56_fu_954_p2;
        add_ln58_5_reg_1706 <= add_ln58_5_fu_880_p2;
        add_ln58_5_reg_1706_pp0_iter1_reg <= add_ln58_5_reg_1706;
        add_ln58_5_reg_1706_pp0_iter2_reg <= add_ln58_5_reg_1706_pp0_iter1_reg;
        cmp38_1_2_reg_1712 <= cmp38_1_2_fu_892_p3;
        cmp38_1_2_reg_1712_pp0_iter1_reg <= cmp38_1_2_reg_1712;
        cmp38_1_2_reg_1712_pp0_iter2_reg <= cmp38_1_2_reg_1712_pp0_iter1_reg;
        cmp38_1_2_reg_1712_pp0_iter3_reg <= cmp38_1_2_reg_1712_pp0_iter2_reg;
        cmp38_1_2_reg_1712_pp0_iter4_reg <= cmp38_1_2_reg_1712_pp0_iter3_reg;
        cmp38_1_reg_1701 <= cmp38_1_fu_872_p3;
        cmp38_1_reg_1701_pp0_iter1_reg <= cmp38_1_reg_1701;
        cmp38_1_reg_1701_pp0_iter2_reg <= cmp38_1_reg_1701_pp0_iter1_reg;
        cmp38_1_reg_1701_pp0_iter3_reg <= cmp38_1_reg_1701_pp0_iter2_reg;
        cmp38_2_1_reg_1722 <= cmp38_2_1_fu_908_p3;
        cmp38_2_1_reg_1722_pp0_iter1_reg <= cmp38_2_1_reg_1722;
        cmp38_2_1_reg_1722_pp0_iter2_reg <= cmp38_2_1_reg_1722_pp0_iter1_reg;
        cmp38_2_1_reg_1722_pp0_iter3_reg <= cmp38_2_1_reg_1722_pp0_iter2_reg;
        cmp38_2_1_reg_1722_pp0_iter4_reg <= cmp38_2_1_reg_1722_pp0_iter3_reg;
        cmp38_2_2_reg_1727 <= cmp38_2_2_fu_916_p3;
        cmp38_2_2_reg_1727_pp0_iter1_reg <= cmp38_2_2_reg_1727;
        cmp38_2_2_reg_1727_pp0_iter2_reg <= cmp38_2_2_reg_1727_pp0_iter1_reg;
        cmp38_2_2_reg_1727_pp0_iter3_reg <= cmp38_2_2_reg_1727_pp0_iter2_reg;
        cmp38_2_2_reg_1727_pp0_iter4_reg <= cmp38_2_2_reg_1727_pp0_iter3_reg;
        cmp38_2_reg_1717 <= cmp38_2_fu_900_p3;
        cmp38_2_reg_1717_pp0_iter1_reg <= cmp38_2_reg_1717;
        cmp38_2_reg_1717_pp0_iter2_reg <= cmp38_2_reg_1717_pp0_iter1_reg;
        cmp38_2_reg_1717_pp0_iter3_reg <= cmp38_2_reg_1717_pp0_iter2_reg;
        cmp38_2_reg_1717_pp0_iter4_reg <= cmp38_2_reg_1717_pp0_iter3_reg;
        cmp38_3_reg_1696 <= cmp38_3_fu_864_p3;
        cmp38_3_reg_1696_pp0_iter1_reg <= cmp38_3_reg_1696;
        cmp38_3_reg_1696_pp0_iter2_reg <= cmp38_3_reg_1696_pp0_iter1_reg;
        cmp38_3_reg_1696_pp0_iter3_reg <= cmp38_3_reg_1696_pp0_iter2_reg;
        cmp38_s_reg_1691 <= cmp38_s_fu_856_p3;
        cmp38_s_reg_1691_pp0_iter1_reg <= cmp38_s_reg_1691;
        cmp38_s_reg_1691_pp0_iter2_reg <= cmp38_s_reg_1691_pp0_iter1_reg;
        cmp38_s_reg_1691_pp0_iter3_reg <= cmp38_s_reg_1691_pp0_iter2_reg;
        cmp_reg_1679 <= cmp_fu_838_p3;
        cmp_reg_1679_pp0_iter1_reg <= cmp_reg_1679;
        cmp_reg_1679_pp0_iter2_reg <= cmp_reg_1679_pp0_iter1_reg;
        cmp_reg_1679_pp0_iter3_reg <= cmp_reg_1679_pp0_iter2_reg;
        icmp_ln50_reg_1639 <= icmp_ln50_fu_756_p2;
        icmp_ln50_reg_1639_pp0_iter1_reg <= icmp_ln50_reg_1639;
        icmp_ln50_reg_1639_pp0_iter2_reg <= icmp_ln50_reg_1639_pp0_iter1_reg;
        icmp_ln50_reg_1639_pp0_iter3_reg <= icmp_ln50_reg_1639_pp0_iter2_reg;
        icmp_ln57_reg_1771 <= icmp_ln57_fu_1007_p2;
        lshr_ln58_1_reg_1684 <= {{select_ln50_fu_780_p3[4:2]}};
        lshr_ln58_1_reg_1684_pp0_iter1_reg <= lshr_ln58_1_reg_1684;
        lshr_ln58_1_reg_1684_pp0_iter2_reg <= lshr_ln58_1_reg_1684_pp0_iter1_reg;
        lshr_ln58_1_reg_1684_pp0_iter3_reg <= lshr_ln58_1_reg_1684_pp0_iter2_reg;
        select_ln50_1_reg_1649 <= select_ln50_1_fu_800_p3;
        select_ln50_1_reg_1649_pp0_iter1_reg <= select_ln50_1_reg_1649;
        select_ln50_1_reg_1649_pp0_iter2_reg <= select_ln50_1_reg_1649_pp0_iter1_reg;
        select_ln50_1_reg_1649_pp0_iter3_reg <= select_ln50_1_reg_1649_pp0_iter2_reg;
        select_ln50_1_reg_1649_pp0_iter4_reg <= select_ln50_1_reg_1649_pp0_iter3_reg;
        select_ln50_2_reg_1656 <= select_ln50_2_fu_808_p3;
        select_ln50_2_reg_1656_pp0_iter1_reg <= select_ln50_2_reg_1656;
        select_ln50_2_reg_1656_pp0_iter2_reg <= select_ln50_2_reg_1656_pp0_iter1_reg;
        select_ln50_reg_1643 <= select_ln50_fu_780_p3;
        select_ln50_reg_1643_pp0_iter1_reg <= select_ln50_reg_1643;
        select_ln50_reg_1643_pp0_iter2_reg <= select_ln50_reg_1643_pp0_iter1_reg;
        tmp_39_reg_1749 <= add_ln56_fu_954_p2[32'd5];
        tmp_44_reg_1776 <= add_ln56_2_fu_971_p2[32'd5];
        tmp_46_reg_1782 <= {{mul_ln58_fu_1058_p2[20:13]}};
        tmp_46_reg_1782_pp0_iter4_reg <= tmp_46_reg_1782;
        trunc_ln1_reg_1766 <= {{add_ln56_2_fu_971_p2[5:2]}};
        trunc_ln51_reg_1669 <= trunc_ln51_fu_834_p1;
        trunc_ln51_reg_1669_pp0_iter1_reg <= trunc_ln51_reg_1669;
        trunc_ln51_reg_1669_pp0_iter2_reg <= trunc_ln51_reg_1669_pp0_iter1_reg;
        trunc_ln51_reg_1669_pp0_iter3_reg <= trunc_ln51_reg_1669_pp0_iter2_reg;
        trunc_ln51_reg_1669_pp0_iter4_reg <= trunc_ln51_reg_1669_pp0_iter3_reg;
        trunc_ln58_reg_1754 <= trunc_ln58_fu_967_p1;
        trunc_ln63_reg_1662 <= trunc_ln63_fu_816_p1;
        trunc_ln63_reg_1662_pp0_iter1_reg <= trunc_ln63_reg_1662;
        trunc_ln63_reg_1662_pp0_iter2_reg <= trunc_ln63_reg_1662_pp0_iter1_reg;
        trunc_ln63_reg_1662_pp0_iter3_reg <= trunc_ln63_reg_1662_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_34_reg_1999 <= acc_34_fu_1540_p3;
        add_ln56_3_reg_1732 <= add_ln56_3_fu_934_p2;
        add_ln56_3_reg_1732_pp0_iter1_reg <= add_ln56_3_reg_1732;
        add_ln56_3_reg_1732_pp0_iter2_reg <= add_ln56_3_reg_1732_pp0_iter1_reg;
        add_ln56_3_reg_1732_pp0_iter3_reg <= add_ln56_3_reg_1732_pp0_iter2_reg;
        add_ln56_3_reg_1732_pp0_iter4_reg <= add_ln56_3_reg_1732_pp0_iter3_reg;
        add_ln58_10_reg_1922 <= add_ln58_10_fu_1225_p2;
        add_ln58_9_reg_1912 <= add_ln58_9_fu_1209_p2;
        icmp_ln57_1_reg_1907 <= icmp_ln57_1_fu_1203_p2;
        lshr_ln58_2_reg_1739 <= {{add_ln56_3_fu_934_p2[5:2]}};
        lshr_ln58_2_reg_1739_pp0_iter1_reg <= lshr_ln58_2_reg_1739;
        lshr_ln58_2_reg_1739_pp0_iter2_reg <= lshr_ln58_2_reg_1739_pp0_iter1_reg;
        tmp_s_reg_1917 <= {{add_ln58_fu_1088_p2[7:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_734 <= grp_fu_711_p11;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_4_reg_1933 <= grp_fu_688_p11;
    end
end

always @ (*) begin
    if (((icmp_ln50_reg_1639 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln50_reg_1639_pp0_iter3_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_iw_load = 6'd0;
    end else begin
        ap_sig_allocacmp_iw_load = iw_fu_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_oh_load = 6'd0;
    end else begin
        ap_sig_allocacmp_oh_load = oh_fu_166;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_1_fu_1556_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_1_fu_1556_p1 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_1_fu_1556_p1 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln58_1_fu_1556_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln58_1_fu_1556_p1 == 3'd0) & ~(trunc_ln58_1_fu_1556_p1 == 3'd1) & ~(trunc_ln58_1_fu_1556_p1 == 3'd2) & ~(trunc_ln58_1_fu_1556_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_665_p10 = trunc_ln51_reg_1669_pp0_iter4_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_665_p10 = trunc_ln51_reg_1669_pp0_iter3_reg;
        end else begin
            grp_fu_665_p10 = 'bx;
        end
    end else begin
        grp_fu_665_p10 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_688_p10 = trunc_ln51_reg_1669_pp0_iter4_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_688_p10 = trunc_ln51_reg_1669_pp0_iter3_reg;
        end else begin
            grp_fu_688_p10 = 'bx;
        end
    end else begin
        grp_fu_688_p10 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_711_p10 = trunc_ln51_reg_1669_pp0_iter4_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_711_p10 = trunc_ln51_reg_1669_pp0_iter3_reg;
        end else begin
            grp_fu_711_p10 = 'bx;
        end
    end else begin
        grp_fu_711_p10 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_0_address0_local = zext_ln58_12_fu_1432_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_0_address0_local = zext_ln58_11_fu_1424_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_0_address0_local = zext_ln58_10_fu_1411_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_0_address0_local = zext_ln58_9_fu_1176_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_0_address0_local = zext_ln58_8_fu_1162_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_0_address0_local = zext_ln58_4_fu_1148_p1;
    end else begin
        img_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_402)) begin
        if (((icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3))) begin
            img_0_address1_local = zext_ln58_3_fu_1134_p1;
        end else if (((tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0))) begin
            img_0_address1_local = zext_ln58_1_fu_1117_p1;
        end else if ((trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1)) begin
            img_0_address1_local = zext_ln58_fu_1103_p1;
        end else begin
            img_0_address1_local = 'bx;
        end
    end else begin
        img_0_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_0_ce0_local = 1'b1;
    end else begin
        img_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_0_ce1_local = 1'b1;
    end else begin
        img_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_1_address0_local = zext_ln58_12_fu_1432_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_1_address0_local = zext_ln58_11_fu_1424_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_1_address0_local = zext_ln58_10_fu_1411_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_1_address0_local = zext_ln58_9_fu_1176_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_1_address0_local = zext_ln58_8_fu_1162_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_1_address0_local = zext_ln58_4_fu_1148_p1;
    end else begin
        img_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_402)) begin
        if (((icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0))) begin
            img_1_address1_local = zext_ln58_3_fu_1134_p1;
        end else if (((tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1))) begin
            img_1_address1_local = zext_ln58_1_fu_1117_p1;
        end else if ((trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2)) begin
            img_1_address1_local = zext_ln58_fu_1103_p1;
        end else begin
            img_1_address1_local = 'bx;
        end
    end else begin
        img_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_1_ce0_local = 1'b1;
    end else begin
        img_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_1_ce1_local = 1'b1;
    end else begin
        img_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_2_address0_local = zext_ln58_12_fu_1432_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_2_address0_local = zext_ln58_11_fu_1424_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_2_address0_local = zext_ln58_10_fu_1411_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_2_address0_local = zext_ln58_9_fu_1176_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_2_address0_local = zext_ln58_8_fu_1162_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_2_address0_local = zext_ln58_4_fu_1148_p1;
    end else begin
        img_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_402)) begin
        if (((icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1))) begin
            img_2_address1_local = zext_ln58_3_fu_1134_p1;
        end else if (((tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2))) begin
            img_2_address1_local = zext_ln58_1_fu_1117_p1;
        end else if ((trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3)) begin
            img_2_address1_local = zext_ln58_fu_1103_p1;
        end else begin
            img_2_address1_local = 'bx;
        end
    end else begin
        img_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_2_ce0_local = 1'b1;
    end else begin
        img_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_2_ce1_local = 1'b1;
    end else begin
        img_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_3_address0_local = zext_ln58_12_fu_1432_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_3_address0_local = zext_ln58_11_fu_1424_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_3_address0_local = zext_ln58_10_fu_1411_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_3_address0_local = zext_ln58_9_fu_1176_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_3_address0_local = zext_ln58_8_fu_1162_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_3_address0_local = zext_ln58_4_fu_1148_p1;
    end else begin
        img_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_402)) begin
        if (((icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2))) begin
            img_3_address1_local = zext_ln58_3_fu_1134_p1;
        end else if (((tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3))) begin
            img_3_address1_local = zext_ln58_1_fu_1117_p1;
        end else if ((trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0)) begin
            img_3_address1_local = zext_ln58_fu_1103_p1;
        end else begin
            img_3_address1_local = 'bx;
        end
    end else begin
        img_3_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_44_reg_1776 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln57_1_reg_1907 == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_3_ce0_local = 1'b1;
    end else begin
        img_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln57_reg_1771 == 1'd1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (tmp_39_reg_1749 == 1'd0) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (trunc_ln51_reg_1669_pp0_iter3_reg == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_3_ce1_local = 1'b1;
    end else begin
        img_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter4_stage0) & (ap_idle_pp0_0to3 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_fu_1378_p3 = ((icmp_ln57_reg_1771[0:0] == 1'b1) ? acc_42_fu_1371_p3 : acc_6_fu_1329_p3);

assign acc_16_fu_1404_p3 = ((tmp_44_reg_1776[0:0] == 1'b1) ? acc_10_fu_1378_p3 : acc_45_fu_1397_p3);

assign acc_22_fu_1272_p3 = ((cmp_reg_1679_pp0_iter3_reg[0:0] == 1'b1) ? v_fu_1243_p11 : acc_fu_1266_p2);

assign acc_24_fu_1487_p3 = ((tmp_47_fu_1461_p3[0:0] == 1'b1) ? acc_48_fu_1454_p3 : acc_51_fu_1480_p3);

assign acc_27_fu_1310_p2 = (v_1_fu_1287_p11 + acc_2_fu_1279_p3);

assign acc_29_fu_1316_p2 = (acc_2_fu_1279_p3 - v_1_fu_1287_p11);

assign acc_2_fu_1279_p3 = ((tmp_41_fu_1235_p3[0:0] == 1'b1) ? 32'd0 : acc_22_fu_1272_p3);

assign acc_30_fu_1514_p3 = ((icmp_ln57_1_reg_1907[0:0] == 1'b1) ? acc_54_fu_1507_p3 : acc_24_fu_1487_p3);

assign acc_34_fu_1540_p3 = ((tmp_40_fu_1439_p3[0:0] == 1'b1) ? acc_30_fu_1514_p3 : acc_57_fu_1533_p3);

assign acc_35_fu_1322_p3 = ((cmp38_s_reg_1691_pp0_iter3_reg[0:0] == 1'b1) ? acc_27_fu_1310_p2 : acc_29_fu_1316_p2);

assign acc_37_fu_1359_p2 = (v_2_fu_1336_p11 + acc_6_fu_1329_p3);

assign acc_40_fu_1589_p3 = ((tmp_50_fu_1564_p3[0:0] == 1'b1) ? acc_34_reg_1999 : acc_60_fu_1582_p3);

assign acc_41_fu_1365_p2 = (acc_6_fu_1329_p3 - v_2_fu_1336_p11);

assign acc_42_fu_1371_p3 = ((cmp38_3_reg_1696_pp0_iter3_reg[0:0] == 1'b1) ? acc_37_fu_1359_p2 : acc_41_fu_1365_p2);

assign acc_43_fu_1385_p2 = (grp_fu_665_p11 + acc_10_fu_1378_p3);

assign acc_44_fu_1391_p2 = (acc_10_fu_1378_p3 - grp_fu_665_p11);

assign acc_45_fu_1397_p3 = ((cmp38_1_reg_1701_pp0_iter3_reg[0:0] == 1'b1) ? acc_43_fu_1385_p2 : acc_44_fu_1391_p2);

assign acc_46_fu_1446_p2 = (v_4_reg_1933 + acc_16_reg_1927);

assign acc_47_fu_1450_p2 = (acc_16_reg_1927 - v_4_reg_1933);

assign acc_48_fu_1454_p3 = ((cmp38_1_1[0:0] == 1'b1) ? acc_46_fu_1446_p2 : acc_47_fu_1450_p2);

assign acc_49_fu_1468_p2 = (reg_734 + acc_48_fu_1454_p3);

assign acc_50_fu_1474_p2 = (acc_48_fu_1454_p3 - reg_734);

assign acc_51_fu_1480_p3 = ((cmp38_1_2_reg_1712_pp0_iter4_reg[0:0] == 1'b1) ? acc_49_fu_1468_p2 : acc_50_fu_1474_p2);

assign acc_52_fu_1495_p2 = (grp_fu_665_p11 + acc_24_fu_1487_p3);

assign acc_53_fu_1501_p2 = (acc_24_fu_1487_p3 - grp_fu_665_p11);

assign acc_54_fu_1507_p3 = ((cmp38_2_reg_1717_pp0_iter4_reg[0:0] == 1'b1) ? acc_52_fu_1495_p2 : acc_53_fu_1501_p2);

assign acc_55_fu_1521_p2 = (grp_fu_688_p11 + acc_30_fu_1514_p3);

assign acc_56_fu_1527_p2 = (acc_30_fu_1514_p3 - grp_fu_688_p11);

assign acc_57_fu_1533_p3 = ((cmp38_2_1_reg_1722_pp0_iter4_reg[0:0] == 1'b1) ? acc_55_fu_1521_p2 : acc_56_fu_1527_p2);

assign acc_58_fu_1572_p2 = (reg_734 + acc_34_reg_1999);

assign acc_59_fu_1577_p2 = (acc_34_reg_1999 - reg_734);

assign acc_60_fu_1582_p3 = ((cmp38_2_2_reg_1727_pp0_iter4_reg[0:0] == 1'b1) ? acc_58_fu_1572_p2 : acc_59_fu_1577_p2);

assign acc_6_fu_1329_p3 = ((tmp_39_reg_1749[0:0] == 1'b1) ? acc_2_fu_1279_p3 : acc_35_fu_1322_p3);

assign acc_fu_1266_p2 = (32'd0 - v_fu_1243_p11);

assign add_ln50_fu_762_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln56_1_fu_788_p2 = (ap_sig_allocacmp_oh_load + 6'd2);

assign add_ln56_2_fu_971_p2 = ($signed(select_ln50_reg_1643_pp0_iter2_reg) + $signed(6'd63));

assign add_ln56_3_fu_934_p2 = (select_ln50_reg_1643 + 6'd1);

assign add_ln56_4_fu_794_p2 = (ap_sig_allocacmp_oh_load + 6'd1);

assign add_ln56_fu_954_p2 = ($signed(select_ln50_2_reg_1656_pp0_iter2_reg) + $signed(6'd63));

assign add_ln58_10_fu_1225_p2 = (zext_ln58_2_fu_1125_p1 + add_ln58_fu_1088_p2);

assign add_ln58_1_fu_1097_p2 = ($signed(sext_ln58_fu_1094_p1) + $signed(shl_ln1_fu_1074_p3));

assign add_ln58_2_fu_1111_p3 = {{trunc_ln58_reg_1754}, {lshr_ln58_1_reg_1684_pp0_iter3_reg}};

assign add_ln58_3_fu_1128_p2 = (zext_ln58_2_fu_1125_p1 + shl_ln1_fu_1074_p3);

assign add_ln58_4_fu_1142_p2 = ($signed(sext_ln58_fu_1094_p1) + $signed(shl_ln58_1_fu_1081_p3));

assign add_ln58_5_fu_880_p2 = (zext_ln51_fu_830_p1 + zext_ln56_fu_826_p1);

assign add_ln58_6_fu_1048_p2 = (zext_ln58_5_fu_1021_p1 + sub_ln58_fu_1042_p2);

assign add_ln58_7_fu_1156_p3 = {{trunc_ln63_reg_1662_pp0_iter3_reg}, {lshr_ln58_1_reg_1684_pp0_iter3_reg}};

assign add_ln58_8_fu_1170_p2 = (zext_ln58_2_fu_1125_p1 + shl_ln58_1_fu_1081_p3);

assign add_ln58_9_fu_1209_p2 = ($signed(sext_ln58_fu_1094_p1) + $signed(add_ln58_fu_1088_p2));

assign add_ln58_fu_1088_p2 = (shl_ln58_1_fu_1081_p3 + 8'd8);

assign add_ln58_s_fu_1418_p3 = {{tmp_s_reg_1917}, {lshr_ln58_1_reg_1684_pp0_iter3_reg}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_402 = ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0 = zext_ln58_7_fu_1548_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_d0 = acc_40_fu_1589_p3;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0 = zext_ln58_7_fu_1548_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_d0 = acc_40_fu_1589_p3;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0 = zext_ln58_7_fu_1548_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_d0 = acc_40_fu_1589_p3;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0 = zext_ln58_7_fu_1548_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_d0 = acc_40_fu_1589_p3;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0 = zext_ln58_7_fu_1548_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_d0 = acc_40_fu_1589_p3;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_we0_local;

assign grp_fu_665_p9 = 'bx;

assign grp_fu_688_p9 = 'bx;

assign grp_fu_711_p9 = 'bx;

assign grp_fu_886_p0 = (zext_ln51_fu_830_p1 + zext_ln56_fu_826_p1);

assign grp_fu_886_p1 = 7'd5;

assign icmp_ln50_fu_756_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_774_p2 = ((ap_sig_allocacmp_iw_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln57_1_fu_1203_p2 = ((tmp_49_fu_1196_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_1007_p2 = ((tmp_43_fu_999_p3 == 2'd0) ? 1'b1 : 1'b0);

assign img_0_address0 = img_0_address0_local;

assign img_0_address1 = img_0_address1_local;

assign img_0_ce0 = img_0_ce0_local;

assign img_0_ce1 = img_0_ce1_local;

assign img_1_address0 = img_1_address0_local;

assign img_1_address1 = img_1_address1_local;

assign img_1_ce0 = img_1_ce0_local;

assign img_1_ce1 = img_1_ce1_local;

assign img_2_address0 = img_2_address0_local;

assign img_2_address1 = img_2_address1_local;

assign img_2_ce0 = img_2_ce0_local;

assign img_2_ce1 = img_2_ce1_local;

assign img_3_address0 = img_3_address0_local;

assign img_3_address1 = img_3_address1_local;

assign img_3_ce0 = img_3_ce0_local;

assign img_3_ce1 = img_3_ce1_local;

assign mul_ln58_fu_1058_p0 = mul_ln58_fu_1058_p00;

assign mul_ln58_fu_1058_p00 = add_ln58_6_fu_1048_p2;

assign mul_ln58_fu_1058_p1 = 21'd1639;

assign or_ln57_1_fu_986_p2 = (add_ln56_fu_954_p2 | add_ln56_3_reg_1732_pp0_iter2_reg);

assign or_ln57_2_fu_1184_p2 = (select_ln50_1_reg_1649_pp0_iter3_reg | add_ln56_2_reg_1760);

assign or_ln57_3_fu_1560_p2 = (select_ln50_1_reg_1649_pp0_iter4_reg | add_ln56_3_reg_1732_pp0_iter4_reg);

assign or_ln57_fu_1231_p2 = (add_ln56_reg_1744 | add_ln56_2_reg_1760);

assign p_shl_fu_1024_p3 = {{trunc_ln63_reg_1662_pp0_iter2_reg}, {5'd0}};

assign select_ln50_1_fu_800_p3 = ((icmp_ln51_fu_774_p2[0:0] == 1'b1) ? add_ln56_1_fu_788_p2 : add_ln56_4_fu_794_p2);

assign select_ln50_2_fu_808_p3 = ((icmp_ln51_fu_774_p2[0:0] == 1'b1) ? add_ln56_4_fu_794_p2 : ap_sig_allocacmp_oh_load);

assign select_ln50_fu_780_p3 = ((icmp_ln51_fu_774_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_iw_load);

assign sext_ln58_fu_1094_p1 = $signed(trunc_ln1_reg_1766);

assign shl_ln1_fu_1074_p3 = {{trunc_ln58_reg_1754}, {3'd0}};

assign shl_ln58_1_fu_1081_p3 = {{trunc_ln63_reg_1662_pp0_iter3_reg}, {3'd0}};

assign shl_ln63_fu_820_p2 = select_ln50_2_fu_808_p3 << 6'd1;

assign sub_ln58_fu_1042_p2 = (p_shl_fu_1024_p3 - zext_ln58_6_fu_1038_p1);

assign tmp_39_fu_959_p3 = add_ln56_fu_954_p2[32'd5];

assign tmp_40_fu_1439_p3 = select_ln50_1_reg_1649_pp0_iter4_reg[32'd5];

assign tmp_41_fu_1235_p3 = or_ln57_fu_1231_p2[32'd5];

assign tmp_42_fu_991_p3 = or_ln57_1_fu_986_p2[32'd5];

assign tmp_43_fu_999_p3 = {{tmp_39_fu_959_p3}, {tmp_42_fu_991_p3}};

assign tmp_45_fu_1031_p3 = {{select_ln50_2_reg_1656_pp0_iter2_reg}, {1'd0}};

assign tmp_47_fu_1461_p3 = add_ln56_3_reg_1732_pp0_iter3_reg[32'd5];

assign tmp_48_fu_1188_p3 = or_ln57_2_fu_1184_p2[32'd5];

assign tmp_49_fu_1196_p3 = {{tmp_44_reg_1776}, {tmp_48_fu_1188_p3}};

assign tmp_50_fu_1564_p3 = or_ln57_3_fu_1560_p2[32'd5];

assign trunc_ln51_fu_834_p1 = select_ln50_fu_780_p3[1:0];

assign trunc_ln58_1_fu_1556_p1 = grp_fu_886_p2[2:0];

assign trunc_ln58_fu_967_p1 = add_ln56_fu_954_p2[4:0];

assign trunc_ln63_fu_816_p1 = select_ln50_2_fu_808_p3[4:0];

assign v_1_fu_1287_p9 = 'bx;

assign v_2_fu_1336_p9 = 'bx;

assign v_fu_1243_p9 = 'bx;

assign zext_ln51_fu_830_p1 = select_ln50_fu_780_p3;

assign zext_ln56_fu_826_p1 = shl_ln63_fu_820_p2;

assign zext_ln58_10_fu_1411_p1 = add_ln58_9_reg_1912;

assign zext_ln58_11_fu_1424_p1 = add_ln58_s_fu_1418_p3;

assign zext_ln58_12_fu_1432_p1 = add_ln58_10_reg_1922;

assign zext_ln58_1_fu_1117_p1 = add_ln58_2_fu_1111_p3;

assign zext_ln58_2_fu_1125_p1 = lshr_ln58_2_reg_1739_pp0_iter2_reg;

assign zext_ln58_3_fu_1134_p1 = add_ln58_3_fu_1128_p2;

assign zext_ln58_4_fu_1148_p1 = add_ln58_4_fu_1142_p2;

assign zext_ln58_5_fu_1021_p1 = add_ln58_5_reg_1706_pp0_iter2_reg;

assign zext_ln58_6_fu_1038_p1 = tmp_45_fu_1031_p3;

assign zext_ln58_7_fu_1548_p1 = tmp_46_reg_1782_pp0_iter4_reg;

assign zext_ln58_8_fu_1162_p1 = add_ln58_7_fu_1156_p3;

assign zext_ln58_9_fu_1176_p1 = add_ln58_8_fu_1170_p2;

assign zext_ln58_fu_1103_p1 = add_ln58_1_fu_1097_p2;

endmodule //bnn_top_bnn_top_Pipeline_VITIS_LOOP_50_2_VITIS_LOOP_51_3
