// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module bnn_top_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        shl_ln2,
        sext_ln104,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_d0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_address0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0,
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] shl_ln2;
input  [31:0] sext_ln104;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_d0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0;
output  [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1;
input  [31:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_d0;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_d0;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_d0;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_d0;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_d0;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_d0;
output  [8:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_address0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0;
output   bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0;
output  [0:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln96_fu_465_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [39:0] sext_ln104_cast_fu_443_p1;
reg  signed [39:0] sext_ln104_cast_reg_988;
wire   [3:0] select_ln96_1_fu_503_p3;
reg   [3:0] select_ln96_1_reg_997;
reg   [3:0] select_ln96_1_reg_997_pp0_iter1_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter2_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter3_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter4_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter5_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter6_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter7_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter8_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter9_reg;
reg   [3:0] select_ln96_1_reg_997_pp0_iter10_reg;
wire   [2:0] trunc_ln99_fu_511_p1;
reg   [2:0] trunc_ln99_reg_1003;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter1_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter2_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter3_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter4_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter5_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter6_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter7_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter8_reg;
reg   [2:0] trunc_ln99_reg_1003_pp0_iter9_reg;
wire   [2:0] trunc_ln97_fu_525_p1;
reg   [2:0] trunc_ln97_reg_1011;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter1_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter2_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter3_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter4_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter5_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter6_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter7_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter8_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter9_reg;
reg   [2:0] trunc_ln97_reg_1011_pp0_iter10_reg;
wire   [4:0] add_ln99_fu_539_p2;
reg   [4:0] add_ln99_reg_1018;
reg   [4:0] add_ln99_reg_1018_pp0_iter1_reg;
reg   [4:0] add_ln99_reg_1018_pp0_iter2_reg;
reg   [4:0] add_ln99_reg_1018_pp0_iter3_reg;
reg   [4:0] add_ln99_reg_1018_pp0_iter4_reg;
reg   [4:0] add_ln99_reg_1018_pp0_iter5_reg;
reg   [4:0] add_ln99_reg_1018_pp0_iter6_reg;
reg   [4:0] add_ln99_reg_1018_pp0_iter7_reg;
reg   [4:0] add_ln99_reg_1018_pp0_iter8_reg;
wire   [2:0] trunc_ln99_1_fu_590_p1;
reg   [2:0] trunc_ln99_1_reg_1024;
reg   [2:0] trunc_ln99_1_reg_1024_pp0_iter9_reg;
reg   [2:0] trunc_ln99_1_reg_1024_pp0_iter10_reg;
wire   [31:0] m_1_fu_833_p3;
reg   [31:0] m_1_reg_1132;
wire   [63:0] zext_ln99_4_fu_647_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln100_fu_686_p1;
wire   [63:0] zext_ln101_fu_779_p1;
wire   [63:0] zext_ln102_fu_818_p1;
wire   [63:0] zext_ln104_fu_849_p1;
reg   [3:0] pw_fu_110;
wire   [3:0] add_ln97_fu_569_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_pw_load;
reg   [3:0] ph_fu_114;
reg   [3:0] ap_sig_allocacmp_ph_load;
reg   [6:0] indvar_flatten36_fu_118;
wire   [6:0] add_ln96_fu_471_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten36_load;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;
reg   [7:0] bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local;
wire   [0:0] icmp_ln104_fu_949_p2;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local;
reg    bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local;
wire   [0:0] icmp_ln97_fu_483_p2;
wire   [3:0] add_ln96_1_fu_497_p2;
wire   [3:0] shl_ln99_fu_515_p2;
wire   [3:0] select_ln96_fu_489_p3;
wire   [3:0] shl_ln99_1_fu_529_p2;
wire   [4:0] zext_ln99_1_fu_535_p1;
wire   [4:0] zext_ln99_fu_521_p1;
wire   [4:0] grp_fu_545_p0;
wire   [3:0] grp_fu_545_p1;
wire   [2:0] grp_fu_545_p2;
wire   [4:0] tmp_fu_604_p3;
wire   [7:0] p_shl_fu_597_p3;
wire   [7:0] zext_ln99_3_fu_611_p1;
wire   [7:0] zext_ln99_2_fu_594_p1;
wire   [7:0] sub_ln99_fu_615_p2;
wire   [7:0] add_ln99_1_fu_621_p2;
wire   [7:0] mul_ln99_fu_631_p0;
wire   [9:0] mul_ln99_fu_631_p1;
wire   [16:0] mul_ln99_fu_631_p2;
wire   [5:0] tmp_1_fu_637_p4;
wire   [7:0] add_ln4_fu_656_p5;
wire   [7:0] mul_ln100_fu_670_p0;
wire   [9:0] mul_ln100_fu_670_p1;
wire   [16:0] mul_ln100_fu_670_p2;
wire   [5:0] tmp_2_fu_676_p4;
wire   [31:0] s0_fu_695_p11;
wire   [31:0] s1_fu_722_p11;
wire   [7:0] add_ln5_fu_749_p5;
wire   [7:0] mul_ln101_fu_763_p0;
wire   [9:0] mul_ln101_fu_763_p1;
wire   [16:0] mul_ln101_fu_763_p2;
wire   [5:0] tmp_3_fu_769_p4;
wire   [7:0] add_ln6_fu_788_p5;
wire   [7:0] mul_ln102_fu_802_p0;
wire   [9:0] mul_ln102_fu_802_p1;
wire   [16:0] mul_ln102_fu_802_p2;
wire   [5:0] tmp_4_fu_808_p4;
wire   [31:0] s1_fu_722_p13;
wire   [31:0] s0_fu_695_p13;
wire   [0:0] icmp_ln103_fu_827_p2;
wire   [8:0] zext_ln96_fu_841_p1;
wire   [8:0] add_ln104_fu_844_p2;
wire   [31:0] s2_fu_861_p11;
wire   [31:0] s3_fu_888_p11;
wire   [31:0] s2_fu_861_p13;
wire   [0:0] icmp_ln103_1_fu_915_p2;
wire   [31:0] s3_fu_888_p13;
wire   [31:0] m_3_fu_920_p3;
wire   [0:0] icmp_ln103_2_fu_927_p2;
wire   [31:0] select_ln103_fu_933_p3;
wire   [39:0] shl_ln104_1_fu_941_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [16:0] mul_ln100_fu_670_p00;
wire   [16:0] mul_ln101_fu_763_p00;
wire   [16:0] mul_ln102_fu_802_p00;
wire   [16:0] mul_ln99_fu_631_p00;
wire   [2:0] s0_fu_695_p1;
wire   [2:0] s0_fu_695_p3;
wire   [2:0] s0_fu_695_p5;
wire   [2:0] s0_fu_695_p7;
wire  signed [2:0] s0_fu_695_p9;
wire  signed [2:0] s1_fu_722_p1;
wire   [2:0] s1_fu_722_p3;
wire   [2:0] s1_fu_722_p5;
wire   [2:0] s1_fu_722_p7;
wire   [2:0] s1_fu_722_p9;
wire  signed [2:0] s2_fu_861_p1;
wire   [2:0] s2_fu_861_p3;
wire   [2:0] s2_fu_861_p5;
wire   [2:0] s2_fu_861_p7;
wire   [2:0] s2_fu_861_p9;
wire   [2:0] s3_fu_888_p1;
wire  signed [2:0] s3_fu_888_p3;
wire   [2:0] s3_fu_888_p5;
wire   [2:0] s3_fu_888_p7;
wire   [2:0] s3_fu_888_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 pw_fu_110 = 4'd0;
#0 ph_fu_114 = 4'd0;
#0 indvar_flatten36_fu_118 = 7'd0;
#0 ap_done_reg = 1'b0;
end

bnn_top_urem_5ns_4ns_3_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_5ns_4ns_3_9_1_U105(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_545_p0),
    .din1(grp_fu_545_p1),
    .ce(1'b1),
    .dout(grp_fu_545_p2)
);

bnn_top_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U106(
    .din0(mul_ln99_fu_631_p0),
    .din1(mul_ln99_fu_631_p1),
    .dout(mul_ln99_fu_631_p2)
);

bnn_top_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U107(
    .din0(mul_ln100_fu_670_p0),
    .din1(mul_ln100_fu_670_p1),
    .dout(mul_ln100_fu_670_p2)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U108(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1),
    .def(s0_fu_695_p11),
    .sel(trunc_ln99_1_reg_1024_pp0_iter9_reg),
    .dout(s0_fu_695_p13)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h0 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h2 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h3 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U109(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q1),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q1),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q1),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q1),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q1),
    .def(s1_fu_722_p11),
    .sel(trunc_ln99_1_reg_1024_pp0_iter9_reg),
    .dout(s1_fu_722_p13)
);

bnn_top_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U110(
    .din0(mul_ln101_fu_763_p0),
    .din1(mul_ln101_fu_763_p1),
    .dout(mul_ln101_fu_763_p2)
);

bnn_top_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U111(
    .din0(mul_ln102_fu_802_p0),
    .din1(mul_ln102_fu_802_p1),
    .dout(mul_ln102_fu_802_p2)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h0 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h2 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h3 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U112(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0),
    .def(s2_fu_861_p11),
    .sel(trunc_ln99_1_reg_1024_pp0_iter10_reg),
    .dout(s2_fu_861_p13)
);

(* dissolve_hierarchy = "yes" *) bnn_top_sparsemux_11_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h0 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h1 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h2 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_11_3_32_1_1_U113(
    .din0(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_q0),
    .din1(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_q0),
    .din2(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_q0),
    .din3(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_q0),
    .din4(bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_q0),
    .def(s3_fu_888_p11),
    .sel(trunc_ln99_1_reg_1024_pp0_iter10_reg),
    .dout(s3_fu_888_p13)
);

bnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln96_fu_465_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten36_fu_118 <= add_ln96_fu_471_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten36_fu_118 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln96_fu_465_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ph_fu_114 <= select_ln96_1_fu_503_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ph_fu_114 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln96_fu_465_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            pw_fu_110 <= add_ln97_fu_569_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            pw_fu_110 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln99_reg_1018 <= add_ln99_fu_539_p2;
        add_ln99_reg_1018_pp0_iter1_reg <= add_ln99_reg_1018;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln96_1_reg_997 <= select_ln96_1_fu_503_p3;
        select_ln96_1_reg_997_pp0_iter1_reg <= select_ln96_1_reg_997;
        sext_ln104_cast_reg_988 <= sext_ln104_cast_fu_443_p1;
        trunc_ln97_reg_1011 <= trunc_ln97_fu_525_p1;
        trunc_ln97_reg_1011_pp0_iter1_reg <= trunc_ln97_reg_1011;
        trunc_ln99_reg_1003 <= trunc_ln99_fu_511_p1;
        trunc_ln99_reg_1003_pp0_iter1_reg <= trunc_ln99_reg_1003;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln99_reg_1018_pp0_iter2_reg <= add_ln99_reg_1018_pp0_iter1_reg;
        add_ln99_reg_1018_pp0_iter3_reg <= add_ln99_reg_1018_pp0_iter2_reg;
        add_ln99_reg_1018_pp0_iter4_reg <= add_ln99_reg_1018_pp0_iter3_reg;
        add_ln99_reg_1018_pp0_iter5_reg <= add_ln99_reg_1018_pp0_iter4_reg;
        add_ln99_reg_1018_pp0_iter6_reg <= add_ln99_reg_1018_pp0_iter5_reg;
        add_ln99_reg_1018_pp0_iter7_reg <= add_ln99_reg_1018_pp0_iter6_reg;
        add_ln99_reg_1018_pp0_iter8_reg <= add_ln99_reg_1018_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        m_1_reg_1132 <= m_1_fu_833_p3;
        select_ln96_1_reg_997_pp0_iter10_reg <= select_ln96_1_reg_997_pp0_iter9_reg;
        select_ln96_1_reg_997_pp0_iter2_reg <= select_ln96_1_reg_997_pp0_iter1_reg;
        select_ln96_1_reg_997_pp0_iter3_reg <= select_ln96_1_reg_997_pp0_iter2_reg;
        select_ln96_1_reg_997_pp0_iter4_reg <= select_ln96_1_reg_997_pp0_iter3_reg;
        select_ln96_1_reg_997_pp0_iter5_reg <= select_ln96_1_reg_997_pp0_iter4_reg;
        select_ln96_1_reg_997_pp0_iter6_reg <= select_ln96_1_reg_997_pp0_iter5_reg;
        select_ln96_1_reg_997_pp0_iter7_reg <= select_ln96_1_reg_997_pp0_iter6_reg;
        select_ln96_1_reg_997_pp0_iter8_reg <= select_ln96_1_reg_997_pp0_iter7_reg;
        select_ln96_1_reg_997_pp0_iter9_reg <= select_ln96_1_reg_997_pp0_iter8_reg;
        trunc_ln97_reg_1011_pp0_iter10_reg <= trunc_ln97_reg_1011_pp0_iter9_reg;
        trunc_ln97_reg_1011_pp0_iter2_reg <= trunc_ln97_reg_1011_pp0_iter1_reg;
        trunc_ln97_reg_1011_pp0_iter3_reg <= trunc_ln97_reg_1011_pp0_iter2_reg;
        trunc_ln97_reg_1011_pp0_iter4_reg <= trunc_ln97_reg_1011_pp0_iter3_reg;
        trunc_ln97_reg_1011_pp0_iter5_reg <= trunc_ln97_reg_1011_pp0_iter4_reg;
        trunc_ln97_reg_1011_pp0_iter6_reg <= trunc_ln97_reg_1011_pp0_iter5_reg;
        trunc_ln97_reg_1011_pp0_iter7_reg <= trunc_ln97_reg_1011_pp0_iter6_reg;
        trunc_ln97_reg_1011_pp0_iter8_reg <= trunc_ln97_reg_1011_pp0_iter7_reg;
        trunc_ln97_reg_1011_pp0_iter9_reg <= trunc_ln97_reg_1011_pp0_iter8_reg;
        trunc_ln99_1_reg_1024 <= trunc_ln99_1_fu_590_p1;
        trunc_ln99_1_reg_1024_pp0_iter10_reg <= trunc_ln99_1_reg_1024_pp0_iter9_reg;
        trunc_ln99_1_reg_1024_pp0_iter9_reg <= trunc_ln99_1_reg_1024;
        trunc_ln99_reg_1003_pp0_iter2_reg <= trunc_ln99_reg_1003_pp0_iter1_reg;
        trunc_ln99_reg_1003_pp0_iter3_reg <= trunc_ln99_reg_1003_pp0_iter2_reg;
        trunc_ln99_reg_1003_pp0_iter4_reg <= trunc_ln99_reg_1003_pp0_iter3_reg;
        trunc_ln99_reg_1003_pp0_iter5_reg <= trunc_ln99_reg_1003_pp0_iter4_reg;
        trunc_ln99_reg_1003_pp0_iter6_reg <= trunc_ln99_reg_1003_pp0_iter5_reg;
        trunc_ln99_reg_1003_pp0_iter7_reg <= trunc_ln99_reg_1003_pp0_iter6_reg;
        trunc_ln99_reg_1003_pp0_iter8_reg <= trunc_ln99_reg_1003_pp0_iter7_reg;
        trunc_ln99_reg_1003_pp0_iter9_reg <= trunc_ln99_reg_1003_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_465_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten36_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten36_load = indvar_flatten36_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ph_load = 4'd0;
    end else begin
        ap_sig_allocacmp_ph_load = ph_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_pw_load = 4'd0;
    end else begin
        ap_sig_allocacmp_pw_load = pw_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd4))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd3))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd0))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = zext_ln102_fu_818_p1;
        end else if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = zext_ln101_fu_779_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024 == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = zext_ln100_fu_686_p1;
        end else if ((trunc_ln99_1_reg_1024 == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = zext_ln99_4_fu_647_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd1)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd2)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = zext_ln102_fu_818_p1;
        end else if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = zext_ln101_fu_779_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024 == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = zext_ln100_fu_686_p1;
        end else if ((trunc_ln99_1_reg_1024 == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = zext_ln99_4_fu_647_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd0)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd1)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = zext_ln102_fu_818_p1;
        end else if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = zext_ln101_fu_779_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024 == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = zext_ln100_fu_686_p1;
        end else if ((trunc_ln99_1_reg_1024 == 3'd1)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = zext_ln99_4_fu_647_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd4)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd0)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = zext_ln102_fu_818_p1;
        end else if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = zext_ln101_fu_779_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024 == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = zext_ln100_fu_686_p1;
        end else if ((trunc_ln99_1_reg_1024 == 3'd0)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = zext_ln99_4_fu_647_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd4)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd0)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd2))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd7))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd6))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (trunc_ln97_reg_1011_pp0_iter10_reg == 3'd5))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd2)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = zext_ln102_fu_818_p1;
        end else if ((trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = zext_ln101_fu_779_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((trunc_ln99_1_reg_1024 == 3'd3)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = zext_ln100_fu_686_p1;
        end else if ((trunc_ln99_1_reg_1024 == 3'd4)) begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = zext_ln99_4_fu_647_p1;
        end else begin
            bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = 'bx;
        end
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln99_1_reg_1024_pp0_iter9_reg == 3'd2)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln99_1_reg_1024 == 3'd3)))) begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local = 1'b1;
    end else begin
        bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln104_fu_844_p2 = (zext_ln96_fu_841_p1 + shl_ln2);

assign add_ln4_fu_656_p5 = {{{{trunc_ln99_reg_1003_pp0_iter8_reg}, {1'd0}}, {trunc_ln97_reg_1011_pp0_iter8_reg}}, {1'd1}};

assign add_ln5_fu_749_p5 = {{{{trunc_ln99_reg_1003_pp0_iter9_reg}, {1'd1}}, {trunc_ln97_reg_1011_pp0_iter9_reg}}, {1'd0}};

assign add_ln6_fu_788_p5 = {{{{trunc_ln99_reg_1003_pp0_iter9_reg}, {1'd1}}, {trunc_ln97_reg_1011_pp0_iter9_reg}}, {1'd1}};

assign add_ln96_1_fu_497_p2 = (ap_sig_allocacmp_ph_load + 4'd1);

assign add_ln96_fu_471_p2 = (ap_sig_allocacmp_indvar_flatten36_load + 7'd1);

assign add_ln97_fu_569_p2 = (select_ln96_fu_489_p3 + 4'd1);

assign add_ln99_1_fu_621_p2 = (zext_ln99_2_fu_594_p1 + sub_ln99_fu_615_p2);

assign add_ln99_fu_539_p2 = (zext_ln99_1_fu_535_p1 + zext_ln99_fu_521_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_10_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_11_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_12_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_1_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_2_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_3_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_4_ce1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_5_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_6_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_7_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_8_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_address0 = zext_ln104_fu_849_p1;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_d0 = icmp_ln104_fu_949_p2;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_9_we0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_address1_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce0_local;

assign bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1 = bnn_top_int_const_unsigned_int_const_int_const_unsigned_int_const_int_co_ce1_local;

assign grp_fu_545_p0 = (zext_ln99_1_fu_535_p1 + zext_ln99_fu_521_p1);

assign grp_fu_545_p1 = 5'd5;

assign icmp_ln103_1_fu_915_p2 = (($signed(s2_fu_861_p13) > $signed(m_1_reg_1132)) ? 1'b1 : 1'b0);

assign icmp_ln103_2_fu_927_p2 = (($signed(s3_fu_888_p13) > $signed(m_3_fu_920_p3)) ? 1'b1 : 1'b0);

assign icmp_ln103_fu_827_p2 = (($signed(s1_fu_722_p13) > $signed(s0_fu_695_p13)) ? 1'b1 : 1'b0);

assign icmp_ln104_fu_949_p2 = (($signed(shl_ln104_1_fu_941_p3) > $signed(sext_ln104_cast_reg_988)) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_465_p2 = ((ap_sig_allocacmp_indvar_flatten36_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_483_p2 = ((ap_sig_allocacmp_pw_load == 4'd8) ? 1'b1 : 1'b0);

assign m_1_fu_833_p3 = ((icmp_ln103_fu_827_p2[0:0] == 1'b1) ? s1_fu_722_p13 : s0_fu_695_p13);

assign m_3_fu_920_p3 = ((icmp_ln103_1_fu_915_p2[0:0] == 1'b1) ? s2_fu_861_p13 : m_1_reg_1132);

assign mul_ln100_fu_670_p0 = mul_ln100_fu_670_p00;

assign mul_ln100_fu_670_p00 = add_ln4_fu_656_p5;

assign mul_ln100_fu_670_p1 = 17'd410;

assign mul_ln101_fu_763_p0 = mul_ln101_fu_763_p00;

assign mul_ln101_fu_763_p00 = add_ln5_fu_749_p5;

assign mul_ln101_fu_763_p1 = 17'd410;

assign mul_ln102_fu_802_p0 = mul_ln102_fu_802_p00;

assign mul_ln102_fu_802_p00 = add_ln6_fu_788_p5;

assign mul_ln102_fu_802_p1 = 17'd410;

assign mul_ln99_fu_631_p0 = mul_ln99_fu_631_p00;

assign mul_ln99_fu_631_p00 = add_ln99_1_fu_621_p2;

assign mul_ln99_fu_631_p1 = 17'd410;

assign p_shl_fu_597_p3 = {{trunc_ln99_reg_1003_pp0_iter8_reg}, {5'd0}};

assign s0_fu_695_p11 = 'bx;

assign s1_fu_722_p11 = 'bx;

assign s2_fu_861_p11 = 'bx;

assign s3_fu_888_p11 = 'bx;

assign select_ln103_fu_933_p3 = ((icmp_ln103_2_fu_927_p2[0:0] == 1'b1) ? s3_fu_888_p13 : m_3_fu_920_p3);

assign select_ln96_1_fu_503_p3 = ((icmp_ln97_fu_483_p2[0:0] == 1'b1) ? add_ln96_1_fu_497_p2 : ap_sig_allocacmp_ph_load);

assign select_ln96_fu_489_p3 = ((icmp_ln97_fu_483_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_pw_load);

assign sext_ln104_cast_fu_443_p1 = $signed(sext_ln104);

assign shl_ln104_1_fu_941_p3 = {{select_ln103_fu_933_p3}, {8'd0}};

assign shl_ln99_1_fu_529_p2 = select_ln96_fu_489_p3 << 4'd1;

assign shl_ln99_fu_515_p2 = select_ln96_1_fu_503_p3 << 4'd1;

assign sub_ln99_fu_615_p2 = (p_shl_fu_597_p3 - zext_ln99_3_fu_611_p1);

assign tmp_1_fu_637_p4 = {{mul_ln99_fu_631_p2[16:11]}};

assign tmp_2_fu_676_p4 = {{mul_ln100_fu_670_p2[16:11]}};

assign tmp_3_fu_769_p4 = {{mul_ln101_fu_763_p2[16:11]}};

assign tmp_4_fu_808_p4 = {{mul_ln102_fu_802_p2[16:11]}};

assign tmp_fu_604_p3 = {{select_ln96_1_reg_997_pp0_iter8_reg}, {1'd0}};

assign trunc_ln97_fu_525_p1 = select_ln96_fu_489_p3[2:0];

assign trunc_ln99_1_fu_590_p1 = grp_fu_545_p2[2:0];

assign trunc_ln99_fu_511_p1 = select_ln96_1_fu_503_p3[2:0];

assign zext_ln100_fu_686_p1 = tmp_2_fu_676_p4;

assign zext_ln101_fu_779_p1 = tmp_3_fu_769_p4;

assign zext_ln102_fu_818_p1 = tmp_4_fu_808_p4;

assign zext_ln104_fu_849_p1 = add_ln104_fu_844_p2;

assign zext_ln96_fu_841_p1 = select_ln96_1_reg_997_pp0_iter10_reg;

assign zext_ln99_1_fu_535_p1 = shl_ln99_1_fu_529_p2;

assign zext_ln99_2_fu_594_p1 = add_ln99_reg_1018_pp0_iter8_reg;

assign zext_ln99_3_fu_611_p1 = tmp_fu_604_p3;

assign zext_ln99_4_fu_647_p1 = tmp_1_fu_637_p4;

assign zext_ln99_fu_521_p1 = shl_ln99_fu_515_p2;

endmodule //bnn_top_bnn_top_Pipeline_VITIS_LOOP_96_14_VITIS_LOOP_97_15
